# -*- coding: utf-8 -*-
"""知识节点题池补充批次 D：写作 4 节点 + 新节点「动词接续（doing与to do）」。
主批次在 kb_questions_a/b/c.py（由题池分工产生），本文件由主会话手写补齐
50 节点全覆盖。schema 与 a/b/c 完全一致，verified=False（未人工复核）。

节点：写作高级句型 / 写作衔接与过渡 / 读后续写技巧 / 应用文写作结构 /
     动词接续（doing与to do）
"""
QUESTIONS = [
    # ---------- 写作高级句型（变体：强调句型 / 倒装与虚拟 / 分词作状语 / with与there be结构） ----------
    {"node": "写作高级句型", "variant": "强调句型", "kind": "choice",
     "stem": "It was not until he returned home ______ he realized what had happened.",
     "options": ["A. when", "B. that", "C. then", "D. since"], "answer": "B",
     "explain": "not until 结构强调时只能用强调句型 It was not until... that...，that 后用肯定式；when 是状语从句连词，构不成强调。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作高级句型", "variant": "倒装与虚拟", "kind": "choice",
     "stem": "Only then ______ realize the importance of working together.",
     "options": ["A. did I", "B. I did", "C. do I", "D. I do"], "answer": "A",
     "explain": "only 修饰状语（only then / only then did I）置于句首时句子部分倒装：助动词提前；then 表过去，用 did。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作高级句型", "variant": "分词作状语", "kind": "choice",
     "stem": "______ from the top of the mountain, the city looks like a beautiful garden.",
     "options": ["A. Seeing", "B. Seen", "C. To see", "D. Saw"], "answer": "B",
     "explain": "主语 the city 是「被看」的对象，用过去分词 Seen 表被动；（When it is）seen from... 是写作中常用的状语从句省略高级句式。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作高级句型", "variant": "with与there be结构", "kind": "choice",
     "stem": "______ more and more forests destroyed, many animals are losing their homes.",
     "options": ["A. With", "B. As", "C. For", "D. Because"], "answer": "A",
     "explain": "with 复合结构（With + 宾语 + 过去分词 destroyed）表伴随状况；As 后须接完整从句（forests are destroyed），选项缺谓语。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作高级句型", "variant": "强调句型", "kind": "fill",
     "stem": "It was in the library ______ we first met three years ago.",
     "options": [], "answer": "that",
     "explain": "强调句型 It was + 地点 + that...；判断方法：去掉 It was...that 后句子仍完整（We first met in the library...）。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作高级句型", "variant": "倒装与虚拟", "kind": "fill",
     "stem": "If I ______ (be) you, I would take the chance to study abroad.",
     "options": [], "answer": "were",
     "explain": "与现在事实相反的虚拟条件句，主语是 I 时 be 动词一律用 were。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作高级句型", "variant": "分词作状语", "kind": "choice",
     "stem": "The teacher came in, ______ by a group of students.",
     "options": ["A. followed", "B. following", "C. to follow", "D. follow"], "answer": "A",
     "explain": "the teacher 是「被跟」的对象，过去分词 followed 表被动伴随；following 会变成「老师跟着学生」，逻辑反了。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作高级句型", "variant": "with与there be结构", "kind": "choice",
     "stem": "There ______ no bus, we had to walk home in the rain.",
     "options": ["A. being", "B. is", "C. was", "D. be"], "answer": "A",
     "explain": "句子已有谓语 had to walk，前半部分是独立主格/there be 的非谓语形式，用 There being... 表原因状语。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},

    # ---------- 写作衔接与过渡（变体：转折衔接 / 因果衔接 / 递进衔接 / 举例与总结） ----------
    {"node": "写作衔接与过渡", "variant": "转折衔接", "kind": "choice",
     "stem": "The task was hard. ______, they managed to finish it on time.",
     "options": ["A. However", "B. Therefore", "C. Besides", "D. Otherwise"], "answer": "A",
     "explain": "前后句语义相反（难 vs 按时完成），用转折 However；Therefore 表因果、Besides 表递进、Otherwise 表「否则」。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作衔接与过渡", "variant": "因果衔接", "kind": "choice",
     "stem": "He was late for the interview. ______, he missed the chance.",
     "options": ["A. As a result", "B. In addition", "C. For example", "D. On the contrary"], "answer": "A",
     "explain": "迟到导致错失机会，是因果链，用 As a result；In addition 表并列补充。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作衔接与过渡", "variant": "递进衔接", "kind": "choice",
     "stem": "Reading broadens our minds. ______, it improves our writing.",
     "options": ["A. What's more", "B. However", "C. In contrast", "D. Anyway"], "answer": "A",
     "explain": "两个好处是并列递进关系，用 What's more；In contrast/However 表对比转折，与句意不符。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作衔接与过渡", "variant": "举例与总结", "kind": "choice",
     "stem": "Some students prefer online learning. ______, Lucy studies all her courses through the Internet.",
     "options": ["A. For instance", "B. In short", "C. Above all", "D. By the way"], "answer": "A",
     "explain": "用具体人物印证前文的观点，是举例子，用 For instance；In short 表总结、Above all 表「最重要的是」。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作衔接与过渡", "variant": "举例与总结", "kind": "fill",
     "stem": "______ a conclusion, taking exercise benefits both body and mind.",
     "options": [], "answer": "in",
     "explain": "in a conclusion→in conclusion（总结句固定短语）；结尾段常用 In conclusion / In short / To sum up 开头。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作衔接与过渡", "variant": "转折衔接", "kind": "choice",
     "stem": "He tried his best. ______, he failed the exam this time.",
     "options": ["A. Nevertheless", "B. Therefore", "C. Moreover", "D. Thus"], "answer": "A",
     "explain": "努力却失败，语义转折，用 Nevertheless（然而/不过）；Therefore 与 Thus 都表因果。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作衔接与过渡", "variant": "因果衔接", "kind": "choice",
     "stem": "______ the heavy rain, the sports meeting was put off.",
     "options": ["A. Because of", "B. Instead of", "C. In spite of", "D. Apart from"], "answer": "A",
     "explain": "大雨是延期的原因，用 Because of + 名词短语；In spite of 表让步「尽管」。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "写作衔接与过渡", "variant": "转折衔接", "kind": "fill",
     "stem": "Phones help us study. On the one hand, they provide learning apps; on the ______ hand, they may distract us.",
     "options": [], "answer": "other",
     "explain": "On the one hand... on the other hand... 是「一方面……另一方面……」的固定对比结构。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},

    # ---------- 读后续写技巧（变体：情节承接 / 动作与心理描写 / 环境烘托 / 主题升华与结尾） ----------
    {"node": "读后续写技巧", "variant": "情节承接", "kind": "choice",
     "stem": "续写段首句已给出：Para 1: Suddenly, the little boy began to cry. 接下来哪句衔接最自然？",
     "options": ["A. Jane looked around for help, her heart pounding.",
                 "B. The next morning, they packed up and left.",
                 "C. Ten years later, the boy became a doctor.",
                 "D. Jane remembered nothing about that day."], "answer": "A",
     "explain": "续写第一段要立刻承接「突然哭」的冲突，A 的即时反应与紧张心理最连贯；B/C 时间跳跃太快，D 与情节矛盾。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "读后续写技巧", "variant": "动作与心理描写", "kind": "choice",
     "stem": "下列哪句用动作细节（show）而不是直接陈述（tell）表现了「紧张」？",
     "options": ["A. Her hands trembled as she reached for the rope.",
                 "B. She felt something indescribable.",
                 "C. Time passed quickly.",
                 "D. It was a fine day."], "answer": "A",
     "explain": "读后续写提倡 show, don't tell：A 用手抖这个可观察的动作呈现紧张，其余都是空洞陈述或无关信息。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "读后续写技巧", "variant": "环境烘托", "kind": "choice",
     "stem": "要烘托「搜救时气氛紧张」，哪句环境描写最合适？",
     "options": ["A. The wind howled and the sky turned dark.",
                 "B. Birds were singing in the sunshine.",
                 "C. The flowers smelled sweet.",
                 "D. The kitchen was warm and tidy."], "answer": "A",
     "explain": "环境描写要为情绪服务：风声呼啸、天色转暗与紧张的搜救氛围一致；其余三项都是轻松愉快的环境，情绪错位。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "读后续写技巧", "variant": "主题升华与结尾", "kind": "choice",
     "stem": "故事讲 Tom 因陌生人帮助而重拾信心，下列哪句作结尾最能升华主题？",
     "options": ["A. From then on, Tom never missed a chance to help others.",
                 "B. And then he woke up — it was all a dream.",
                 "C. The story ended without any reason.",
                 "D. Tom bought a new car the next year."], "answer": "A",
     "explain": "结尾要让主题落地：A 把「被帮助→去帮助别人」写成行为改变，呼应主题；B「梦境反转」推翻前文、C 无意义、D 偏离主题。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "读后续写技巧", "variant": "主题升华与结尾", "kind": "fill",
     "stem": "The story ended ______ a happy family reunion, which warmed every reader's heart.",
     "options": [], "answer": "with",
     "explain": "end with... 是「以……收尾」的固定搭配，续写结尾常用 end with + 名词短语点出结局。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "读后续写技巧", "variant": "情节承接", "kind": "fill",
     "stem": "The rescuers pulled the boy out of the water ______ (safe). Everyone cheered.",
     "options": [], "answer": "safely",
     "explain": "括号提示词 safe，修饰动词 pulled...out 用副词形式 safely。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "读后续写技巧", "variant": "动作与心理描写", "kind": "choice",
     "stem": "要写出「他害怕」，表达最地道的是哪句？",
     "options": ["A. His heart raced and his legs went weak.",
                 "B. He was very very afraid.",
                 "C. Fear was a feeling in his heart.",
                 "D. He thought fear is bad."], "answer": "A",
     "explain": "A 同时调动身体反应（心跳加速、腿软）让读者「看见」害怕；B 重复堆词、C/D 都是生硬陈述。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "读后续写技巧", "variant": "情节承接", "kind": "choice",
     "stem": "续写必须与前文逻辑一致。前文写 Tom 从小怕狗，下列续写处理正确的是？",
     "options": ["A. Tom saw the dog, froze for a second, and stepped back slowly.",
                 "B. Tom turned out to be a world-famous dog trainer.",
                 "C. A little sister who was never mentioned appeared.",
                 "D. The story jumped to three years later suddenly."], "answer": "A",
     "explain": "续写要延续人物的既有设定：怕狗见到狗仍紧张（A）才连贯；B 人设突变、C/D 无铺垫地新增人物或跳跃时间都破坏一致性。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},

    # ---------- 应用文写作结构（变体：书信开头与结尾 / 建议与邀请的表达 / 通知与演讲格式 / 要点覆盖与得体性） ----------
    {"node": "应用文写作结构", "variant": "书信开头与结尾", "kind": "choice",
     "stem": "邀请外教参加中国文化节，开头最得体的是哪句？",
     "options": ["A. I'm writing to invite you to the Chinese Culture Festival.",
                 "B. As we all know, invitations are very common.",
                 "C. I bought you a gift yesterday.",
                 "D. This letter is about the weather."], "answer": "A",
     "explain": "应用文开头要开门见山点明写信目的：I'm writing to... 是邀请信标准开头；B 空话、C/D 偏题。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "应用文写作结构", "variant": "建议与邀请的表达", "kind": "choice",
     "stem": "建议信中提出建议，语气最得体的是哪句？",
     "options": ["A. I would like to suggest that you join the reading club.",
                 "B. You must join the club right now.",
                 "C. The club is none of your business.",
                 "D. Join it, or you will fail."], "answer": "A",
     "explain": "对同学/外教提建议要委婉：would like to suggest / you might as well 是常用得体句式；B 太命令、C/D 不礼貌。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "应用文写作结构", "variant": "书信开头与结尾", "kind": "choice",
     "stem": "求助信的结尾，最合适的是哪句？",
     "options": ["A. I would appreciate it if you could reply soon.",
                 "B. That's all you need to know.",
                 "C. Never contact me again.",
                 "D. The end."], "answer": "A",
     "explain": "求助信结尾要礼貌表达期待：I would appreciate it if... 是高分句型，同时呼应「求助」的请求语气。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "应用文写作结构", "variant": "通知与演讲格式", "kind": "fill",
     "stem": "______ students are informed that the school meeting has been put off till Friday.",
     "options": [], "answer": "all",
     "explain": "通知面向全体对象：All students are informed that... 是书面通知的常用开头。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "应用文写作结构", "variant": "通知与演讲格式", "kind": "choice",
     "stem": "英语演讲稿的开头，最得体的是哪句？",
     "options": ["A. Good afternoon, everyone. It's a great honor to speak here.",
                 "B. This speech is about something.",
                 "C. Sit down and listen to me.",
                 "D. I have nothing to say."], "answer": "A",
     "explain": "演讲稿开头要有称呼、问候与谦辞：Good afternoon, everyone + It's a great honor... 是标准开场。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "应用文写作结构", "variant": "要点覆盖与得体性", "kind": "choice",
     "stem": "写一封邀请信，下列要点处理最完整的是？",
     "options": ["A. 写清活动时间、地点、内容，并请对方确认是否出席",
                 "B. 只写活动内容，时间地点让对方自己猜",
                 "C. 只介绍自己的爱好和社团规模",
                 "D. 详细抱怨学校食堂的饭菜"], "answer": "A",
     "explain": "邀请信要点：时间、地点、活动内容 + 期待回复（确认出席），缺任一要点都会被扣分。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "应用文写作结构", "variant": "书信开头与结尾", "kind": "fill",
     "stem": "Thank you for your letter. I'm looking forward to ______ (receive) your reply soon.",
     "options": [], "answer": "hearing from",
     "explain": "look forward to + doing；结合句尾 your reply，填 hearing from（收到你的回信）比 receiving 更地道。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "应用文写作结构", "variant": "通知与演讲格式", "kind": "choice",
     "stem": "一份书面通知应当包含哪些要素？",
     "options": ["A. 时间、地点、事件、注意事项和落款",
                 "B. 只有事件内容",
                 "C. 只有落款和日期",
                 "D. 只有个人感受"], "answer": "A",
     "explain": "通知的五要素：时间、地点、事件、注意事项、落款（单位+日期），缺一不可，其余选项要素不全。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},

    # ---------- 动词接续（doing与to do）（变体：+doing类动词 / stop类两态 / remember与forget两态 / manage与mean类） ----------
    {"node": "动词接续（doing与to do）", "variant": "+doing类动词", "kind": "choice",
     "stem": "I enjoy ______ books in my free time.",
     "options": ["A. reading", "B. to read", "C. read", "D. reads"], "answer": "A",
     "explain": "enjoy 后只能接动名词 doing：enjoy doing；to read 会因接续错误丢分。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "动词接续（doing与to do）", "variant": "stop类两态", "kind": "choice",
     "stem": "The bus stopped ______ more passengers on the way.",
     "options": ["A. to pick up", "B. picking up", "C. pick up", "D. picked up"], "answer": "A",
     "explain": "stop to do 表「停下来去做另一件事」（停下行驶去接人）；stop doing 表「停止正在做的事」。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "动词接续（doing与to do）", "variant": "stop类两态", "kind": "choice",
     "stem": "Stop ______! The baby is sleeping.",
     "options": ["A. talking", "B. to talk", "C. talk", "D. talked"], "answer": "A",
     "explain": "让正在做的事停下来用 stop doing（stop talking 别说话了）；stop to talk 变成「停下来去说话」，逻辑相反。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "动词接续（doing与to do）", "variant": "remember与forget两态", "kind": "choice",
     "stem": "Please remember ______ the door when you leave.",
     "options": ["A. to lock", "B. locking", "C. lock", "D. locked"], "answer": "A",
     "explain": "remember to do = 记得要去做（还没做）；remember doing = 记得曾做过。出门前提醒要做的动作用 to lock。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "动词接续（doing与to do）", "variant": "remember与forget两态", "kind": "choice",
     "stem": "I regret ______ your advice last year.",
     "options": ["A. not taking", "B. to take", "C. take", "D. took"], "answer": "A",
     "explain": "regret doing = 后悔做过的事；regret not taking = 后悔「没听劝」这件事已发生，用动名词。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "动词接续（doing与to do）", "variant": "manage与mean类", "kind": "choice",
     "stem": "We managed ______ the task before dark.",
     "options": ["A. to finish", "B. finishing", "C. finish", "D. finished"], "answer": "A",
     "explain": "manage to do 是固定搭配（设法做成某事），后接不定式；manage doing 不是正确接续。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "动词接续（doing与to do）", "variant": "remember与forget两态", "kind": "fill",
     "stem": "I forgot ______ (bring) my keys, so I was locked out of the house.",
     "options": [], "answer": "to bring",
     "explain": "忘了「要去做」用 forget to do（钥匙根本没带，被锁门外印证没做）；forget doing 是忘了「曾做过」。括号提示 bring。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
    {"node": "动词接续（doing与to do）", "variant": "manage与mean类", "kind": "fill",
     "stem": "Missing this train means ______ (wait) for another hour.",
     "options": [], "answer": "waiting",
     "explain": "mean doing = 意味着（某种结果），mean to do = 打算做。误车「意味着」再等一小时，用 waiting。括号提示 wait。",
     "source": "自编练习（2026-08-31，未人工复核）", "verified": False},
]
