# -*- coding: utf-8 -*-
# 自编练习题库B（2026-08-31，未人工复核）：13个知识点 x 8题 = 104题
# node: 省略句 / 祈使句与感叹句 / 情态动词表推测 / need与dare的用法 / 主将从现 /
#       定语从句that与which的选择 / 介词+关系代词 / as引导的定语从句 / 情态动词+have done /
#       名词 / 代词 / 冠词 / 介词

QUESTIONS = [
    # ================= 省略句 =================
    {
        "node": "省略句",
        "variant": "状语从句中的省略",
        "kind": "choice",
        "stem": "When ______ the museum, remember not to touch the exhibits.",
        "options": ["A. visiting", "B. visited", "C. to visit", "D. you will visit"],
        "answer": "A",
        "explain": "when/while/if等引导的状语从句中，主语与主句一致且谓语含be时，可省略主语和be，用when + doing。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "省略句",
        "variant": "状语从句中的省略",
        "kind": "choice",
        "stem": "If ______ to the party, she would have met her old friend.",
        "options": ["A. invited", "B. she was invited", "C. being invited", "D. invite"],
        "answer": "A",
        "explain": "if引导的状语从句中，主语与主句一致且为被动时，可省略主语和be，即if invited = if she had been invited。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "省略句",
        "variant": "状语从句中的省略",
        "kind": "fill",
        "stem": "While ______ (用wait的适当形式) for the bus, I read a short story.",
        "options": [],
        "answer": "waiting",
        "explain": "while引导的状语从句省略主语和be后，动词用现在分词形式waiting。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "省略句",
        "variant": "不定式符号to的省略与保留",
        "kind": "choice",
        "stem": "—Would you like to come to my birthday party? —I'd love ______.",
        "options": ["A. to", "B. love", "C. do", "D. it"],
        "answer": "A",
        "explain": "答语中I'd love to后省略了不定式的内容，但to必须保留。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "省略句",
        "variant": "不定式符号to的省略与保留",
        "kind": "choice",
        "stem": "He didn't come to the meeting though he had promised ______.",
        "options": ["A. to", "B. coming", "C. so", "D. doing"],
        "answer": "A",
        "explain": "promise to do sth在从句语境清楚时可省略do sth，仅保留不定式符号to。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "省略句",
        "variant": "替代词so/not的省略",
        "kind": "fill",
        "stem": "—Will it snow tomorrow? —I hope ______, or the crops will die. (填入替代词)",
        "options": [],
        "answer": "so",
        "explain": "or表示否则，即希望下雪，故用I hope so，so替代前面的从句内容。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "省略句",
        "variant": "替代词so/not的省略",
        "kind": "choice",
        "stem": "—Is Mr. Smith in the office? —I'm afraid ______.",
        "options": ["A. not", "B. so", "C. it", "D. no"],
        "answer": "A",
        "explain": "I'm afraid not为固定省略结构，not替代否定的从句内容。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "省略句",
        "variant": "不定式符号to的省略与保留",
        "kind": "choice",
        "stem": "—Why didn't you attend the lecture? —______, but I was busy preparing for the exam.",
        "options": ["A. I wanted to", "B. I wanted", "C. I'd love", "D. I hoped do"],
        "answer": "A",
        "explain": "省略回答中不定式的内容可省去，但to必须保留，即I wanted to (attend it)。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 祈使句与感叹句 =================
    {
        "node": "祈使句与感叹句",
        "variant": "祈使句+and/or表条件",
        "kind": "choice",
        "stem": "Work hard, ______ you will pass the exam.",
        "options": ["A. and", "B. or", "C. so", "D. but"],
        "answer": "A",
        "explain": "祈使句 + and + 陈述句表顺承条件：努力工作就能通过考试。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "祈使句与感叹句",
        "variant": "祈使句+and/or表条件",
        "kind": "choice",
        "stem": "Hurry up, ______ we will miss the train.",
        "options": ["A. or", "B. and", "C. unless", "D. if"],
        "answer": "A",
        "explain": "祈使句 + or + 陈述句表相反条件：不快点就会误车。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "祈使句与感叹句",
        "variant": "祈使句+and/or表条件",
        "kind": "fill",
        "stem": "______ (用not be的祈使形式) late again, or the teacher will be angry.",
        "options": [],
        "answer": "don't be",
        "explain": "否定祈使句用Don't + 动词原形，即Don't be late again。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "祈使句与感叹句",
        "variant": "what感叹句（修饰名词）",
        "kind": "choice",
        "stem": "______ wonderful music it is! I never get tired of it.",
        "options": ["A. What", "B. What a", "C. How", "D. How a"],
        "answer": "A",
        "explain": "music为不可数名词，感叹句用What + 形容词 + 不可数名词 + 主谓结构。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "祈使句与感叹句",
        "variant": "what感叹句（修饰名词）",
        "kind": "choice",
        "stem": "______ great progress he has made this term!",
        "options": ["A. What", "B. What a", "C. How", "D. How a"],
        "answer": "A",
        "explain": "progress为不可数名词，故用What引导感叹句。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "祈使句与感叹句",
        "variant": "how感叹句（修饰形/副）",
        "kind": "choice",
        "stem": "______ fast the little boy runs! No one can catch up with him.",
        "options": ["A. How", "B. What", "C. What a", "D. How a"],
        "answer": "A",
        "explain": "fast为副词，感叹句用How + 副词 + 主谓结构。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "祈使句与感叹句",
        "variant": "how感叹句（修饰形/副）",
        "kind": "fill",
        "stem": "______ time flies! It seems only yesterday that we entered high school. (填What或How)",
        "options": [],
        "answer": "how",
        "explain": "How time flies为固定感叹句，How修饰动词flies。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "祈使句与感叹句",
        "variant": "否定祈使句",
        "kind": "choice",
        "stem": "______ make so much noise. The baby is sleeping.",
        "options": ["A. Don't", "B. Not", "C. No", "D. Doesn't"],
        "answer": "A",
        "explain": "否定祈使句用Don't + 动词原形，Don't make so much noise。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 情态动词表推测 =================
    {
        "node": "情态动词表推测",
        "variant": "must/can't表必然与不可能",
        "kind": "choice",
        "stem": "The lights in his room are still on, so he ______ be at home.",
        "options": ["A. must", "B. can't", "C. needn't", "D. may not"],
        "answer": "A",
        "explain": "灯还亮着是肯定推测的依据，故用must be表示肯定判断。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词表推测",
        "variant": "must/can't表必然与不可能",
        "kind": "choice",
        "stem": "—The winner of the race is a tall boy with glasses. —It ______ be Tom. He is short and wears nothing on his nose.",
        "options": ["A. can't", "B. mustn't", "C. needn't", "D. shouldn't"],
        "answer": "A",
        "explain": "Tom又矮又不戴眼镜，与描述完全不符，用can't be表示不可能。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词表推测",
        "variant": "may/might表可能性",
        "kind": "choice",
        "stem": "—Where is Lucy? —I'm not sure. She ______ be in the library, but she usually plays basketball at this time.",
        "options": ["A. may", "B. must", "C. can", "D. should"],
        "answer": "A",
        "explain": "I'm not sure表明说话人不确定，用may be表示可能的推测。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词表推测",
        "variant": "may/might表可能性",
        "kind": "choice",
        "stem": "You ______ be right, but I still think we should double-check the data.",
        "options": ["A. may", "B. can", "C. need", "D. shall"],
        "answer": "A",
        "explain": "but后仍建议核对数据，说明说话人不确定，用may be表可能。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词表推测",
        "variant": "must/can't表必然与不可能",
        "kind": "fill",
        "stem": "—Who is knocking at the door? —It ______ be the postman, for he has already been here this morning. (填入适当的情态动词)",
        "options": [],
        "answer": "can't",
        "explain": "邮递员上午已经来过，不可能现在再来，用can't be表否定推测。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词表推测",
        "variant": "may/might表可能性",
        "kind": "fill",
        "stem": "She has been traveling for a whole day without sleep, so she ______ be very tired now. (填入语气最强的推测情态动词)",
        "options": [],
        "answer": "must",
        "explain": "根据一整天没睡觉的客观依据作最有把握的肯定推测，用must be。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词表推测",
        "variant": "推测的疑问式",
        "kind": "choice",
        "stem": "—______ the news be true? —I hardly think so.",
        "options": ["A. Can", "B. Must", "C. Should", "D. Need"],
        "answer": "A",
        "explain": "can用于疑问句表推测，意为可能，Can the news be true?",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词表推测",
        "variant": "根据语境判断推测程度",
        "kind": "choice",
        "stem": "Look at the dark clouds. It ______ rain soon, so let's hurry home.",
        "options": ["A. may", "B. can", "C. need", "D. shall"],
        "answer": "A",
        "explain": "乌云只是下雨的征兆而非必然，用may表不太确定的推测。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= need与dare的用法 =================
    {
        "node": "need与dare的用法",
        "variant": "need作情态动词",
        "kind": "choice",
        "stem": "You needn't ______ the window; it's not cold in here.",
        "options": ["A. close", "B. to close", "C. closing", "D. closed"],
        "answer": "A",
        "explain": "need作情态动词时后接动词原形，needn't close = 不必关。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "need与dare的用法",
        "variant": "need作情态动词",
        "kind": "choice",
        "stem": "—Need I hand in my homework now? —Yes, you ______.",
        "options": ["A. must", "B. need", "C. can", "D. may"],
        "answer": "A",
        "explain": "Need I...?的肯定回答用Yes, you must，否定回答才用needn't。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "need与dare的用法",
        "variant": "dare作情态动词与实义动词",
        "kind": "choice",
        "stem": "How dare you ______ to me like that!",
        "options": ["A. speak", "B. speaks", "C. speaking", "D. to speak"],
        "answer": "A",
        "explain": "How dare you...中dare作情态动词，后接动词原形speak。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "need与dare的用法",
        "variant": "dare作情态动词与实义动词",
        "kind": "choice",
        "stem": "She ______ walk home alone because it was getting dark.",
        "options": ["A. didn't dare to", "B. dared not to", "C. doesn't dare", "D. dare not to"],
        "answer": "A",
        "explain": "dare作实义动词时用didn't dare to do；dare not后不接to，故B、D错误，C时态不对。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "need与dare的用法",
        "variant": "need作实义动词",
        "kind": "fill",
        "stem": "The flowers need ______ (用water的-ing形式) badly, or they will die.",
        "options": [],
        "answer": "watering",
        "explain": "need doing = need to be done，主动形式表被动含义。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "need与dare的用法",
        "variant": "needn't与mustn't辨析",
        "kind": "choice",
        "stem": "You ______ come tomorrow if you are busy; just send me an email.",
        "options": ["A. needn't", "B. mustn't", "C. can't", "D. shouldn't"],
        "answer": "A",
        "explain": "可发邮件代替，说明不必来，用needn't；mustn't表禁止，与语境不符。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "need与dare的用法",
        "variant": "dare作情态动词与实义动词",
        "kind": "fill",
        "stem": "He dare not ______ (用go的适当形式) out alone at night, for the road is dark and empty.",
        "options": [],
        "answer": "go",
        "explain": "dare not为情态动词否定式，后接动词原形go。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "need与dare的用法",
        "variant": "needn't与mustn't辨析",
        "kind": "choice",
        "stem": "—Shall I tell John about the plan? —No, you ______. I've told him already.",
        "options": ["A. needn't", "B. mustn't", "C. wouldn't", "D. shouldn't"],
        "answer": "A",
        "explain": "已经告诉他了，说明没有必要再讲，用needn't表不必。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 主将从现 =================
    {
        "node": "主将从现",
        "variant": "时间连词when/as soon as/until/once",
        "kind": "choice",
        "stem": "I will call you as soon as I ______ the ticket information.",
        "options": ["A. get", "B. will get", "C. got", "D. would get"],
        "answer": "A",
        "explain": "as soon as引导时间状语从句，主句用将来时，从句用一般现在时表将来。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主将从现",
        "variant": "if/unless引导条件状语从句",
        "kind": "choice",
        "stem": "If it ______ tomorrow, the sports meet will be put off.",
        "options": ["A. rains", "B. will rain", "C. rained", "D. would rain"],
        "answer": "A",
        "explain": "if引导真实条件状语从句，主句用将来时，从句用一般现在时。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主将从现",
        "variant": "if/unless引导条件状语从句",
        "kind": "fill",
        "stem": "Unless you ______ (用take的适当形式) more exercise, you won't lose weight.",
        "options": [],
        "answer": "take",
        "explain": "unless引导条件状语从句，主将从现，从句用一般现在时take。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主将从现",
        "variant": "时间连词when/as soon as/until/once",
        "kind": "choice",
        "stem": "We won't start the meeting until the manager ______.",
        "options": ["A. arrives", "B. will arrive", "C. arrived", "D. is arriving"],
        "answer": "A",
        "explain": "until引导时间状语从句，主句用将来时，从句用一般现在时arrives。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主将从现",
        "variant": "宾语从句中仍用将来时（对比陷阱）",
        "kind": "choice",
        "stem": "I don't know when he ______ back, but I'll tell you as soon as he arrives.",
        "options": ["A. will come", "B. comes", "C. came", "D. come"],
        "answer": "A",
        "explain": "此处的when引导宾语从句而非时间状语从句，不适用主将从现，仍用将来时。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主将从现",
        "variant": "if/unless引导条件状语从句",
        "kind": "fill",
        "stem": "If the company ______ (用not improve的适当形式) its service, it will lose more customers.",
        "options": [],
        "answer": "doesn't improve",
        "explain": "if引导条件状语从句用主将从现，否定式为doesn't improve。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主将从现",
        "variant": "if/unless引导条件状语从句",
        "kind": "choice",
        "stem": "You will fail the exam ______ you work much harder.",
        "options": ["A. unless", "B. if", "C. when", "D. until"],
        "answer": "A",
        "explain": "unless = if not，引导条件状语从句，从句仍用一般现在时表将来。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主将从现",
        "variant": "时间连词when/as soon as/until/once",
        "kind": "choice",
        "stem": "Once you ______ a good habit, it will benefit you for life.",
        "options": ["A. form", "B. will form", "C. formed", "D. are forming"],
        "answer": "A",
        "explain": "once引导时间状语从句，主句用将来时，从句用一般现在时form。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 定语从句that与which的选择 =================
    {
        "node": "定语从句that与which的选择",
        "variant": "只能用that的场景",
        "kind": "choice",
        "stem": "Is there anything else ______ you want to say about the plan?",
        "options": ["A. that", "B. which", "C. who", "D. whose"],
        "answer": "A",
        "explain": "先行词为不定代词anything时，定语从句只能用that引导。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句that与which的选择",
        "variant": "只能用that的场景",
        "kind": "choice",
        "stem": "This is the best film ______ I have ever seen.",
        "options": ["A. that", "B. which", "C. what", "D. whom"],
        "answer": "A",
        "explain": "先行词被最高级the best修饰时，关系词只能用that。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句that与which的选择",
        "variant": "只能用which的场景",
        "kind": "choice",
        "stem": "The Great Wall, ______ is one of the wonders of the world, attracts millions of tourists every year.",
        "options": ["A. which", "B. that", "C. what", "D. where"],
        "answer": "A",
        "explain": "非限制性定语从句不能用that，只能用which。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句that与which的选择",
        "variant": "只能用which的场景",
        "kind": "choice",
        "stem": "He was always ready to help others, ______ made everyone like him.",
        "options": ["A. which", "B. that", "C. what", "D. it"],
        "answer": "A",
        "explain": "which指代前面整个主句的内容作从句主语，非限制性定语从句不能用that。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句that与which的选择",
        "variant": "只能用that的场景",
        "kind": "fill",
        "stem": "The singer and her songs ______ I mentioned just now are well known to the students. (填that或which)",
        "options": [],
        "answer": "that",
        "explain": "先行词既有人又有物时，关系词只能用that。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句that与which的选择",
        "variant": "只能用which的场景",
        "kind": "fill",
        "stem": "This is the house in ______ the famous writer was born. (填入关系代词)",
        "options": [],
        "answer": "which",
        "explain": "介词in后的关系代词指物只能用which，不能用that。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句that与which的选择",
        "variant": "只能用that的场景",
        "kind": "choice",
        "stem": "All ______ can be done has been done to save the dying man.",
        "options": ["A. that", "B. which", "C. what", "D. who"],
        "answer": "A",
        "explain": "先行词为all时，定语从句只能用that引导。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句that与which的选择",
        "variant": "that与which通用时的干扰排除",
        "kind": "choice",
        "stem": "The village ______ I visited last summer has changed a lot.",
        "options": ["A. which", "B. what", "C. where", "D. who"],
        "answer": "A",
        "explain": "先行词village作visited的宾语，关系词用which或that均可，what/where/who不符合。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 介词+关系代词 =================
    {
        "node": "介词+关系代词",
        "variant": "介词+which指物",
        "kind": "choice",
        "stem": "This is the lab ______ we often do science experiments.",
        "options": ["A. in which", "B. that", "C. which", "D. what"],
        "answer": "A",
        "explain": "do experiments in the lab，介词in提前后须用in which，相当于where。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词+关系代词",
        "variant": "介词+which指物",
        "kind": "choice",
        "stem": "The pen with ______ he writes is a birthday gift from his father.",
        "options": ["A. which", "B. that", "C. whom", "D. what"],
        "answer": "A",
        "explain": "write with the pen，介词with提前后只能用which，不能用that。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词+关系代词",
        "variant": "介词+whom指人",
        "kind": "choice",
        "stem": "Mr. Wang, from ______ I learned a lot, is a patient teacher.",
        "options": ["A. whom", "B. which", "C. that", "D. him"],
        "answer": "A",
        "explain": "介词from后的关系代词指人只能用whom，不能用that或which。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词+关系代词",
        "variant": "介词+whom指人",
        "kind": "choice",
        "stem": "The old man has two sons, one of ______ is a doctor.",
        "options": ["A. whom", "B. which", "C. them", "D. who"],
        "answer": "A",
        "explain": "介词of后指人用whom；若用them则两个句子无连词连接，不合语法。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词+关系代词",
        "variant": "介词+which指物",
        "kind": "fill",
        "stem": "The house ______ which we spent our holiday last summer was near the sea. (填入一个介词)",
        "options": [],
        "answer": "in",
        "explain": "spend one's holiday in the house，介词in提前与which连用。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词+关系代词",
        "variant": "介词+whom指人",
        "kind": "fill",
        "stem": "The teacher ______ whom the students have great respect will retire next month. (填入一个介词)",
        "options": [],
        "answer": "for",
        "explain": "have great respect for sb，介词for提前与whom连用。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词+关系代词",
        "variant": "介词+which指物",
        "kind": "choice",
        "stem": "I'll never forget the days during ______ we worked together in the countryside.",
        "options": ["A. which", "B. that", "C. when", "D. what"],
        "answer": "A",
        "explain": "during the days，介词during提前后须用during which，不能用when。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词+关系代词",
        "variant": "介词+关系代词与普通关系词辨析",
        "kind": "choice",
        "stem": "The school ______ he once studied for three years has a long history.",
        "options": ["A. in which", "B. which", "C. what", "D. that"],
        "answer": "A",
        "explain": "study in the school，study为不及物用法，缺少介词in，故须用in which。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= as引导的定语从句 =================
    {
        "node": "as引导的定语从句",
        "variant": "such...as",
        "kind": "choice",
        "stem": "This is such an interesting story ______ all of us enjoy reading.",
        "options": ["A. as", "B. that", "C. which", "D. so"],
        "answer": "A",
        "explain": "such...as引导定语从句，as作从句中reading的宾语；such...that则引导结果状语从句，that不作成分，此处enjoy缺宾语，故用as。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "as引导的定语从句",
        "variant": "the same...as",
        "kind": "choice",
        "stem": "Your watch is not the same ______ mine; yours is newer.",
        "options": ["A. as", "B. that", "C. which", "D. than"],
        "answer": "A",
        "explain": "not the same...as为固定搭配，as引导定语从句表示与同类事物比较。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "as引导的定语从句",
        "variant": "as引导非限制性定语从句（可前可后）",
        "kind": "choice",
        "stem": "______ is known to all, the earth moves around the sun.",
        "options": ["A. As", "B. It", "C. Which", "D. What"],
        "answer": "A",
        "explain": "as引导非限制性定语从句可位于句首，指代整个主句；which只能后置。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "as引导的定语从句",
        "variant": "as引导非限制性定语从句（可前可后）",
        "kind": "choice",
        "stem": "He was late again, ______ is often the case.",
        "options": ["A. as", "B. that", "C. what", "D. it"],
        "answer": "A",
        "explain": "as is often the case为固定表达，as指代整个主句且可后置。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "as引导的定语从句",
        "variant": "such...as",
        "kind": "fill",
        "stem": "Don't read such useless books ______ will waste your time. (填入关系词)",
        "options": [],
        "answer": "as",
        "explain": "such...as引导定语从句，as在从句中作主语。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "as引导的定语从句",
        "variant": "as引导非限制性定语从句（可前可后）",
        "kind": "fill",
        "stem": "______ is often the case with children, Tom got tired of the game quickly. (填入关系词)",
        "options": [],
        "answer": "as",
        "explain": "as is often the case为固定表达，as引导的非限制性定语从句可位于句首。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "as引导的定语从句",
        "variant": "as与which辨析",
        "kind": "choice",
        "stem": "Alice received an invitation from her boss, ______ came as a surprise.",
        "options": ["A. which", "B. that", "C. as", "D. what"],
        "answer": "A",
        "explain": "此处指代主句中收请柬这一具体事件，用which引导非限制性定语从句；as多与know/expect等固定搭配。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "as引导的定语从句",
        "variant": "such...as",
        "kind": "choice",
        "stem": "We have made such great progress ______ you described in your letter.",
        "options": ["A. as", "B. which", "C. that", "D. what"],
        "answer": "A",
        "explain": "such...as引导定语从句，as作described的宾语；such...that中that不作成分，而described缺宾语。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 情态动词+have done =================
    {
        "node": "情态动词+have done",
        "variant": "must/can't have done表过去推测",
        "kind": "choice",
        "stem": "The light in his room is still on, so he ______ have gone to bed.",
        "options": ["A. can't", "B. must", "C. shouldn't", "D. needn't"],
        "answer": "A",
        "explain": "灯还亮着说明不可能已入睡，用can't have done表对过去的否定推测。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词+have done",
        "variant": "must/can't have done表过去推测",
        "kind": "choice",
        "stem": "It usually takes her three days to write a report, so she ______ have finished it within one day.",
        "options": ["A. can't", "B. mustn't", "C. shouldn't", "D. wouldn't"],
        "answer": "A",
        "explain": "一天不可能写完通常需要三天的报告，用can't have done表否定推测。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词+have done",
        "variant": "should( shouldn't) have done表责备",
        "kind": "choice",
        "stem": "You ______ have returned the book to the library last Friday; now you have to pay a fine.",
        "options": ["A. should", "B. could", "C. might", "D. need"],
        "answer": "A",
        "explain": "should have done表示本应该做而没做，含责备意味，与被罚款的事实吻合。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词+have done",
        "variant": "should( shouldn't) have done表责备",
        "kind": "choice",
        "stem": "He looks upset. You ______ have told him the bad news so directly.",
        "options": ["A. shouldn't", "B. mustn't", "C. needn't", "D. can't"],
        "answer": "A",
        "explain": "shouldn't have done表示本不应该做却做了，含责备意味。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词+have done",
        "variant": "needn't have done表本不必做",
        "kind": "fill",
        "stem": "I ______ have taken a taxi; the bus was quite fast and cheap. (填入适当的情态动词)",
        "options": [],
        "answer": "needn't",
        "explain": "乘公共汽车既快又便宜，说明本来不必打车，用needn't have done。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词+have done",
        "variant": "must/can't have done表过去推测",
        "kind": "fill",
        "stem": "The streets are all wet, so it ______ have rained hard last night. (填入适当的情态动词)",
        "options": [],
        "answer": "must",
        "explain": "街道全湿是昨夜下大雨的确定依据，用must have done表对过去的肯定推测。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词+have done",
        "variant": "may/might have done表过去可能",
        "kind": "choice",
        "stem": "—Where is Mr. Li? He was here a moment ago. —He ______ have gone to the teachers' office; I'm not sure.",
        "options": ["A. may", "B. must", "C. should", "D. can"],
        "answer": "A",
        "explain": "I'm not sure表明不确定，用may have done表对过去的不太确定推测。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词+have done",
        "variant": "should( shouldn't) have done表责备",
        "kind": "choice",
        "stem": "—I stayed up late playing games last night. —You ______ have gone to bed earlier. Health comes first.",
        "options": ["A. should", "B. must", "C. need", "D. will"],
        "answer": "A",
        "explain": "should have done表示本应该早点睡而没做到，含责备和建议意味。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 名词 =================
    {
        "node": "名词",
        "variant": "名词词义辨析",
        "kind": "choice",
        "stem": "—What's the ______ like today? —It's sunny and warm.",
        "options": ["A. weather", "B. climate", "C. temperature", "D. condition"],
        "answer": "A",
        "explain": "问今天状况答sunny and warm，用weather（当天天气）；climate指长期气候。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词",
        "variant": "名词词义辨析",
        "kind": "choice",
        "stem": "The teacher gave us a piece of ______ on how to learn English well.",
        "options": ["A. advice", "B. suggestion", "C. information", "D. news"],
        "answer": "A",
        "explain": "a piece of advice为固定搭配；suggestion可数，不能与a piece of连用。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词",
        "variant": "可数与不可数及复数形式",
        "kind": "choice",
        "stem": "The factory has produced a large number of ______ this year.",
        "options": ["A. machines", "B. machineries", "C. equipment", "D. furnitures"],
        "answer": "A",
        "explain": "a large number of后接可数名词复数；machinery/equipment不可数，furniture不可数且无复数。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词",
        "variant": "可数与不可数及复数形式",
        "kind": "fill",
        "stem": "The ______ (用child的适当形式) in this kindergarten are looked after very well.",
        "options": [],
        "answer": "children",
        "explain": "谓语为are，说明主语是复数，child的复数为不规则形式children。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词",
        "variant": "固定搭配中的名词",
        "kind": "fill",
        "stem": "To my ______ (填表示吃惊的名词), I found my lost dog at the school gate this morning.",
        "options": [],
        "answer": "surprise",
        "explain": "to one's surprise为固定搭配，意为令某人吃惊的是。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词",
        "variant": "名词作定语",
        "kind": "choice",
        "stem": "There are many ______ shops near our school.",
        "options": ["A. shoe", "B. shoes", "C. shoes'", "D. of shoes"],
        "answer": "A",
        "explain": "名词作定语修饰另一名词时一般用单数形式，即shoe shops。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词",
        "variant": "可数与不可数及复数形式",
        "kind": "choice",
        "stem": "I'd like two ______ of paper to write on.",
        "options": ["A. pieces", "B. piece", "C. slices", "D. bars"],
        "answer": "A",
        "explain": "paper不可数，表数量用two pieces of paper；slices/bars与paper不搭配。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词",
        "variant": "名词词义辨析",
        "kind": "choice",
        "stem": "He has a good ______ of English history, so he can tell many stories about it.",
        "options": ["A. knowledge", "B. mind", "C. idea", "D. thought"],
        "answer": "A",
        "explain": "have a good knowledge of为固定搭配，意为通晓、了解。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 代词 =================
    {
        "node": "代词",
        "variant": "it/one/that/those的区别",
        "kind": "choice",
        "stem": "The weather in the south is warmer than ______ in the north.",
        "options": ["A. that", "B. it", "C. one", "D. this"],
        "answer": "A",
        "explain": "that代替前面特指的不可数名词the weather，比较对象为两地的weather。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "代词",
        "variant": "it/one/that/those的区别",
        "kind": "choice",
        "stem": "I have lost my pen. I'm looking for ______. Have you seen it?",
        "options": ["A. it", "B. one", "C. that", "D. this"],
        "answer": "A",
        "explain": "it特指前面提到的my pen；one表示泛指的同类另一个。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "代词",
        "variant": "it/one/that/those的区别",
        "kind": "choice",
        "stem": "This jacket doesn't fit me. Please show me a bigger ______.",
        "options": ["A. one", "B. it", "C. this", "D. that"],
        "answer": "A",
        "explain": "要的是另一件同类夹克（泛指），用one；it指原来那件，不合语境。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "代词",
        "variant": "both/either/neither/none的用法",
        "kind": "choice",
        "stem": "—When shall we meet, on Saturday or Sunday? —______ day is OK. I'm free all week.",
        "options": ["A. Either", "B. Both", "C. Neither", "D. None"],
        "answer": "A",
        "explain": "两天中任选一天都可以，用Either；Both后需接days复数。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "代词",
        "variant": "both/either/neither/none的用法",
        "kind": "choice",
        "stem": "There are five apples on the table, but ______ of them is fresh. They have all gone bad.",
        "options": ["A. none", "B. neither", "C. either", "D. all"],
        "answer": "A",
        "explain": "三者以上全否定用none；neither只用于两者。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "代词",
        "variant": "反身代词",
        "kind": "fill",
        "stem": "The little girl looked at ______ in the mirror and smiled. (填入适当的代词)",
        "options": [],
        "answer": "herself",
        "explain": "look at oneself in the mirror照镜子，主语the girl对应反身代词herself。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "代词",
        "variant": "it/one/that/those的区别",
        "kind": "fill",
        "stem": "The population of China is larger than ______ of any other country. (填入适当的代词)",
        "options": [],
        "answer": "that",
        "explain": "that代替特指的the population，构成比较对象the population of...。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "代词",
        "variant": "both/either/neither/none的用法",
        "kind": "choice",
        "stem": "______ of the students in our class has an English-Chinese dictionary.",
        "options": ["A. Each", "B. All", "C. Some", "D. Both"],
        "answer": "A",
        "explain": "Each of...作主语谓语用单数has；All/Some/Both of后谓语用复数。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 冠词 =================
    {
        "node": "冠词",
        "variant": "a/an的音素判断",
        "kind": "choice",
        "stem": "An elephant is ______ useful animal.",
        "options": ["A. a", "B. an", "C. the", "D. /"],
        "answer": "A",
        "explain": "useful以辅音音素/j/开头，用a而不是an。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "冠词",
        "variant": "a/an的音素判断",
        "kind": "choice",
        "stem": "It took me ______ hour to finish the work.",
        "options": ["A. an", "B. a", "C. the", "D. /"],
        "answer": "A",
        "explain": "hour以元音音素/aʊ/开头，用an。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "冠词",
        "variant": "the的特指用法",
        "kind": "choice",
        "stem": "______ Yellow River is the second longest river in China.",
        "options": ["A. The", "B. A", "C. An", "D. /"],
        "answer": "A",
        "explain": "江河名称前用定冠词the，如the Yellow River。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "冠词",
        "variant": "the的特指用法",
        "kind": "fill",
        "stem": "Lily began to learn to play ______ violin at the age of five. (填a, the或/)",
        "options": [],
        "answer": "the",
        "explain": "play + 乐器名词时前面用定冠词the。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "冠词",
        "variant": "零冠词固定场景",
        "kind": "choice",
        "stem": "The old man goes to ______ bed early and gets up early.",
        "options": ["A. /", "B. the", "C. a", "D. an"],
        "answer": "A",
        "explain": "go to bed为固定短语，bed前用零冠词，表示就寝。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "冠词",
        "variant": "a/an的音素判断",
        "kind": "fill",
        "stem": "There is ______ 'u' in the word 'use'. (填a或an)",
        "options": [],
        "answer": "a",
        "explain": "字母u读作/juː/，以辅音音素开头，故用a。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "冠词",
        "variant": "the的特指用法",
        "kind": "choice",
        "stem": "He is ______ taller of the two brothers.",
        "options": ["A. the", "B. a", "C. /", "D. one"],
        "answer": "A",
        "explain": "特指两者中较高者，比较级前用the，即the taller of the two。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "冠词",
        "variant": "a的固定搭配",
        "kind": "choice",
        "stem": "—Did you enjoy your stay in Beijing? —Yes, I had ______ wonderful time.",
        "options": ["A. a", "B. the", "C. /", "D. an"],
        "answer": "A",
        "explain": "have a wonderful time为固定搭配，意为玩得开心。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 介词 =================
    {
        "node": "介词",
        "variant": "时间介词",
        "kind": "choice",
        "stem": "The plane takes off ______ a cold winter morning.",
        "options": ["A. on", "B. in", "C. at", "D. for"],
        "answer": "A",
        "explain": "具体某一天的上午/下午/晚上用介词on，如on a cold winter morning。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词",
        "variant": "时间介词",
        "kind": "choice",
        "stem": "I have lived in this city ______ 2010.",
        "options": ["A. since", "B. for", "C. from", "D. in"],
        "answer": "A",
        "explain": "现在完成时+过去时间点用since；for后接时间段。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词",
        "variant": "地点介词",
        "kind": "choice",
        "stem": "Japan lies ______ the east of China.",
        "options": ["A. to", "B. on", "C. in", "D. at"],
        "answer": "A",
        "explain": "日本不与中国接壤且在本国范围之外，用to the east of；in指范围之内，on指接壤。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词",
        "variant": "地点介词",
        "kind": "choice",
        "stem": "He climbed up the tree and hid himself ______ the leaves.",
        "options": ["A. among", "B. between", "C. over", "D. above"],
        "answer": "A",
        "explain": "among表示在三者或以上的物体（树叶）中间；between用于两者之间。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词",
        "variant": "固定搭配中的介词",
        "kind": "fill",
        "stem": "It's very kind ______ you to help me with my English. (填入适当的介词)",
        "options": [],
        "answer": "of",
        "explain": "It's very kind of sb to do sth为固定搭配，kind描述人的品质用of。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词",
        "variant": "时间介词",
        "kind": "fill",
        "stem": "The library opens ______ Monday to Friday. (填入一个介词)",
        "options": [],
        "answer": "from",
        "explain": "from...to...为固定结构，表示从周一到周五。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词",
        "variant": "besides/except等辨析",
        "kind": "choice",
        "stem": "All the students went to the park ______ Tom, who was ill.",
        "options": ["A. except", "B. besides", "C. beside", "D. with"],
        "answer": "A",
        "explain": "Tom病了没去，表示从整体中除去，用except；besides表示包括在内。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "介词",
        "variant": "固定搭配中的介词",
        "kind": "choice",
        "stem": "He is strict ______ himself, but kind to others.",
        "options": ["A. with", "B. to", "C. for", "D. at"],
        "answer": "A",
        "explain": "be strict with sb为固定搭配，意为对某人要求严格。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
]
