# -*- coding: utf-8 -*-
# 自编练习题库C（2026-08-31，未人工复核）：16个知识点 x 8题 = 128题
# node: 形容词 / 副词 / 连词 / 限定词 / 数词 / 不定代词 / 指代词辨析 / 倍数表达法 /
#       so与such的区别 / 易混动词辨析 / 固定搭配辨析 / 短语动词 / 易混名词辨析 /
#       易混形容词副词辨析 / 近义词辨析 / 词性转换（派生法）

QUESTIONS = [
    # ================= 形容词 =================
    {
        "node": "形容词",
        "variant": "多个形容词的排列顺序",
        "kind": "choice",
        "stem": "She bought a ______ vase at the flea market yesterday.",
        "options": ["A. beautiful little blue Chinese", "B. little beautiful blue Chinese", "C. blue beautiful little Chinese", "D. Chinese beautiful little blue"],
        "answer": "A",
        "explain": "多个形容词修饰名词的顺序为：观点—大小—颜色—产地，故用beautiful little blue Chinese。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "形容词",
        "variant": "多个形容词的排列顺序",
        "kind": "choice",
        "stem": "The ______ man taking photos over there is my grandfather.",
        "options": ["A. old tall German", "B. tall old German", "C. German old tall", "D. old German tall"],
        "answer": "A",
        "explain": "形容词排列顺序为：大小/形状—年龄/新旧—国籍，年龄old在前，国籍German在后。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "形容词",
        "variant": "-ing与-ed形容词",
        "kind": "fill",
        "stem": "The ______ (用bore的适当形式) audience left the hall before the speech ended.",
        "options": [],
        "answer": "bored",
        "explain": "修饰人表示\"感到无聊的\"用-ed形式bored；-ing形式boring表示\"令人无聊的\"，修饰事物。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "形容词",
        "variant": "-ing与-ed形容词",
        "kind": "choice",
        "stem": "The ______ news made all of us ______ that night.",
        "options": ["A. exciting; excited", "B. excited; exciting", "C. exciting; exciting", "D. excited; excited"],
        "answer": "A",
        "explain": "news修饰事物用exciting；us指人表示感受用excited。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "形容词",
        "variant": "-ing与-ed形容词",
        "kind": "choice",
        "stem": "After the two-hour journey, everyone felt ______ and went to bed early.",
        "options": ["A. exhausted", "B. exhausting", "C. exhaust", "D. exhaustion"],
        "answer": "A",
        "explain": "felt是系动词，后接形容词作表语；修饰人表示\"感到疲惫的\"用exhausted。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "形容词",
        "variant": "复合形容词的构成",
        "kind": "choice",
        "stem": "They are going to build a ______ bridge over the river next year.",
        "options": ["A. ten-metre-long", "B. ten-metres-long", "C. ten metre long", "D. ten-metres long"],
        "answer": "A",
        "explain": "复合形容词中的名词用单数且各部分用连字符连接，故为ten-metre-long。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "形容词",
        "variant": "只能作表语的形容词",
        "kind": "choice",
        "stem": "The old fisherman pushed the snake back into the water, and it was still ______.",
        "options": ["A. alive", "B. lively", "C. living", "D. live"],
        "answer": "A",
        "explain": "alive意为\"活着的\"，只能作表语，常与still等连用；live作定语，lively意为\"活泼的\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "形容词",
        "variant": "只能作表语的形容词",
        "kind": "fill",
        "stem": "The baby is ______ (睡着的) now, so please keep quiet in the room.",
        "options": [],
        "answer": "asleep",
        "explain": "asleep意为\"睡着的\"，只能作表语，此处作系动词is的表语。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    # ================= 副词 =================
    {
        "node": "副词",
        "variant": "频度副词与倒装",
        "kind": "choice",
        "stem": "—Do your parents allow you to play computer games on weekdays? —No. ______ are they allowed to do so.",
        "options": ["A. Seldom", "B. Sometimes", "C. Often", "D. Always"],
        "answer": "A",
        "explain": "由No可知频度极低；否定意义频度副词seldom位于句首时句子用部分倒装are they allowed。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "副词",
        "variant": "频度副词与倒装",
        "kind": "choice",
        "stem": "He has ______ been to Beijing; in fact, he has never left his small hometown.",
        "options": ["A. never", "B. ever", "C. already", "D. just"],
        "answer": "A",
        "explain": "由后句never left可知他从没去过北京，用never；ever用于疑问句，already/just与语境矛盾。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "副词",
        "variant": "副词比较级",
        "kind": "choice",
        "stem": "The more carefully you do the exercises, the ______ mistakes you will make.",
        "options": ["A. fewer", "B. less", "C. few", "D. little"],
        "answer": "A",
        "explain": "mistakes为可数名词复数，用few的比较级fewer；less修饰不可数名词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "副词",
        "variant": "副词比较级",
        "kind": "fill",
        "stem": "She sings even ______ (用bad的适当形式) than her elder sister.",
        "options": [],
        "answer": "worse",
        "explain": "than提示用比较级，bad的比较级为worse，even修饰比较级。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "副词",
        "variant": "-ly副词辨析",
        "kind": "choice",
        "stem": "Have you seen Tom ______? He has been absent from class for a whole week.",
        "options": ["A. lately", "B. later", "C. latest", "D. late"],
        "answer": "A",
        "explain": "lately意为\"最近\"，常与现在完成时连用；late指\"晚\"，later指\"后来\"，latest为\"最新的\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "副词",
        "variant": "-ly副词辨析",
        "kind": "choice",
        "stem": "He works very ______, so he seldom has time to travel with his family.",
        "options": ["A. hard", "B. hardly", "C. harder", "D. hardest"],
        "answer": "A",
        "explain": "work hard意为\"努力工作\"；hardly意为\"几乎不\"，与后半句因果逻辑不符。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "副词",
        "variant": "方式、地点、时间的排列顺序",
        "kind": "choice",
        "stem": "The teacher told us to finish the experiment ______ after class.",
        "options": ["A. carefully in the lab", "B. in the lab carefully", "C. carefully after class in the lab", "D. after class carefully in the lab"],
        "answer": "A",
        "explain": "方式、地点、时间副词并列时的顺序为：方式—地点—时间，故用carefully in the lab after class。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "副词",
        "variant": "频度副词与倒装",
        "kind": "fill",
        "stem": "—Do you often go to the city library? —Yes, I go there ______ (每周一次).",
        "options": [],
        "answer": "once a week",
        "explain": "表示频率\"每周一次\"用once a week，频度短语可位于句末。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    # ================= 连词 =================
    {
        "node": "连词",
        "variant": "祈使句+and/or",
        "kind": "choice",
        "stem": "Hurry up, ______ we'll miss the early bus to the museum.",
        "options": ["A. and", "B. or", "C. but", "D. so"],
        "answer": "B",
        "explain": "祈使句+or表示\"否则\"，即如果不赶快就会错过早班车；and表示顺承结果。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "连词",
        "variant": "祈使句+and/or",
        "kind": "choice",
        "stem": "Give me one more minute, ______ I'll have finished writing the address.",
        "options": ["A. or", "B. so", "C. and", "D. but"],
        "answer": "C",
        "explain": "祈使句+and表示\"那么就会\"，此处指再给一分钟就能写完，为顺承结果。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "连词",
        "variant": "从属连词引导状语从句",
        "kind": "choice",
        "stem": "______ it rains tomorrow, the sports meet will be put off till next Friday.",
        "options": ["A. If", "B. Unless", "C. Though", "D. Whether"],
        "answer": "A",
        "explain": "主句说运动会被推迟，条件是明天下雨，用if引导条件状语从句。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "连词",
        "variant": "从属连词引导状语从句",
        "kind": "choice",
        "stem": "I was about to leave the office ______ the telephone rang suddenly.",
        "options": ["A. while", "B. when", "C. as", "D. until"],
        "answer": "B",
        "explain": "be about to do...when...为固定结构，when意为\"这时突然\"，从句用一般过去时。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "连词",
        "variant": "从属连词引导状语从句",
        "kind": "fill",
        "stem": "You will fail the final exam ______ (除非) you work much harder than before.",
        "options": [],
        "answer": "unless",
        "explain": "unless意为\"如果不、除非\"，引导否定条件状语从句，符合句意。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "连词",
        "variant": "关联连词与主谓一致",
        "kind": "choice",
        "stem": "Not only the students but also their teacher ______ invited to the English party last night.",
        "options": ["A. was", "B. were", "C. have been", "D. are"],
        "answer": "A",
        "explain": "not only...but also连接主语时谓语遵循就近原则，与their teacher一致用单数；last night用过去时。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "连词",
        "variant": "并列连词表原因",
        "kind": "choice",
        "stem": "He must be ill, ______ he didn't come to school this morning.",
        "options": ["A. for", "B. so", "C. but", "D. or"],
        "answer": "A",
        "explain": "for是并列连词，表推断性的原因，语气比because弱，用于补充说明前面推测的理由。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "连词",
        "variant": "关联连词与主谓一致",
        "kind": "fill",
        "stem": "______ (不仅) does he sing well, but he also dances well.",
        "options": [],
        "answer": "not only",
        "explain": "not only置于句首时前一分句用部分倒装，且与but also呼应。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    # ================= 限定词 =================
    {
        "node": "限定词",
        "variant": "such与what和冠词的位置",
        "kind": "choice",
        "stem": "______ terrible weather we've been having recently! It has rained for two weeks.",
        "options": ["A. What", "B. What a", "C. How", "D. Such"],
        "answer": "A",
        "explain": "weather为不可数名词，感叹句用What+形容词+不可数名词，不加冠词a。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "限定词",
        "variant": "such与what和冠词的位置",
        "kind": "choice",
        "stem": "She gave me ______ on how to prepare for the interview.",
        "options": ["A. such good advice", "B. such a good advice", "C. a such good advice", "D. so good advice"],
        "answer": "A",
        "explain": "advice为不可数名词，不能加冠词a；such用于名词短语前，语序为such good advice。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "限定词",
        "variant": "half的用法",
        "kind": "choice",
        "stem": "______ of the students in our class come from the countryside.",
        "options": ["A. Half", "B. The half", "C. Half a", "D. A half"],
        "answer": "A",
        "explain": "half of+名词作主语时，half前不加冠词，构成half of the students结构。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "限定词",
        "variant": "half的用法",
        "kind": "fill",
        "stem": "I have read ______ (这本书的一半) already, and I'll finish it tonight.",
        "options": [],
        "answer": "half the book",
        "explain": "half直接放在冠词the之前，构成half the book，表示\"这本书的一半\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "限定词",
        "variant": "few/little与a number of",
        "kind": "choice",
        "stem": "Hurry up! We have ______ time left before the train leaves.",
        "options": ["A. little", "B. a little", "C. few", "D. a few"],
        "answer": "A",
        "explain": "time为不可数名词用little修饰；Hurry up表明时间所剩无几，含否定意义，用little。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "限定词",
        "variant": "few/little与a number of",
        "kind": "choice",
        "stem": "______ students in our school have taken part in the voluntary activity this month.",
        "options": ["A. A number of", "B. The number of", "C. A great deal of", "D. A large amount of"],
        "answer": "A",
        "explain": "a number of+复数名词表示\"许多\"；the number of作主语意为\"……的数量\"；deal of和amount of修饰不可数名词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "限定词",
        "variant": "another与other的辨析",
        "kind": "choice",
        "stem": "This shirt is too small for me. Would you show me ______ one, please?",
        "options": ["A. another", "B. other", "C. the other", "D. others"],
        "answer": "A",
        "explain": "another one表示三者及以上中的\"另一个\"；the other指两者中的另一个；other不能单独修饰one。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "限定词",
        "variant": "another与other的辨析",
        "kind": "fill",
        "stem": "I have two brothers. One is a doctor, and ______ (另一个) is a teacher.",
        "options": [],
        "answer": "the other",
        "explain": "两者中的一个用one，另一个用the other，构成one...the other结构。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

# ================= 数词 =================
    {
        "node": "数词",
        "variant": "分数与百分数的表达",
        "kind": "choice",
        "stem": "______ of the land in that area is covered with trees and grass.",
        "options": ["A. Two fifths", "B. Two fifth", "C. Second fifths", "D. Two five"],
        "answer": "A",
        "explain": "分数表达法：分子用基数词，分母用序数词，分子大于一时分母加s，故为two fifths。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "数词",
        "variant": "分数与百分数的表达",
        "kind": "fill",
        "stem": "The population of the city has increased by ______ (百分之二十) in the past five years.",
        "options": [],
        "answer": "twenty percent",
        "explain": "百分数用基数词+percent表示，百分之二十为twenty percent。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "数词",
        "variant": "基数词复数表约数",
        "kind": "choice",
        "stem": "______ people attended the opening ceremony of the sports meeting yesterday.",
        "options": ["A. Hundreds of", "B. Hundred of", "C. Two hundreds", "D. Several hundreds"],
        "answer": "A",
        "explain": "hundred前有具体数词时不加s、不与of连用；表示约数用hundreds of。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "数词",
        "variant": "复合形容词与时间段",
        "kind": "choice",
        "stem": "The ______ boy won the first prize in the English speech competition.",
        "options": ["A. eight-year-old", "B. eight-years-old", "C. eight year old", "D. eight-years old"],
        "answer": "A",
        "explain": "复合形容词作定语时其中的名词用单数，且用连字符连接，故为eight-year-old。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "数词",
        "variant": "序数词与年龄段",
        "kind": "choice",
        "stem": "Though he is in his ______, my grandfather keeps learning new things on the Internet.",
        "options": ["A. sixties", "B. sixty", "C. sixtieth", "D. sixty's"],
        "answer": "A",
        "explain": "in one's+基数词复数表示\"在某人几十多岁时\"，in his sixties即六十多岁。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "数词",
        "variant": "复合形容词与时间段",
        "kind": "choice",
        "stem": "He finished the difficult task in ______.",
        "options": ["A. two hours and a half", "B. two hour and half", "C. two and half hour", "D. half and two hour"],
        "answer": "A",
        "explain": "\"两个半小时\"可表达为two hours and a half或two and a half hours。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "数词",
        "variant": "序数词与年龄段",
        "kind": "choice",
        "stem": "The Yangtze River is ______ longest river in China, after the Yellow River.",
        "options": ["A. the second", "B. second", "C. the two", "D. a second"],
        "answer": "A",
        "explain": "表示\"第几最……\"用the+序数词+最高级，the second longest即第二长。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "数词",
        "variant": "基数词复数表约数",
        "kind": "fill",
        "stem": "______ (数以千计的) visitors come to visit the museum every year.",
        "options": [],
        "answer": "thousands of",
        "explain": "thousand前无具体数词时用复数加of构成thousands of，表示约数\"数以千计的\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    # ================= 不定代词 =================
    {
        "node": "不定代词",
        "variant": "both/neither/all/none与主谓一致",
        "kind": "choice",
        "stem": "______ of them knows French, so I have to ask a third person for help.",
        "options": ["A. Neither", "B. Either", "C. Both", "D. All"],
        "answer": "A",
        "explain": "谓语knows为单数且需再找第三个人，说明两人都不懂，用neither；both/all作主语谓语用复数。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "不定代词",
        "variant": "both/neither/all/none与主谓一致",
        "kind": "choice",
        "stem": "I invited five friends to my birthday party, but ______ of them came because of the heavy snow.",
        "options": ["A. none", "B. all", "C. neither", "D. both"],
        "answer": "A",
        "explain": "三者及以上全不用none；neither/both只用于两者；由but和snow可知没人来。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "不定代词",
        "variant": "both/neither/all/none与主谓一致",
        "kind": "choice",
        "stem": "All that can be done ______ been done to save the injured man.",
        "options": ["A. has", "B. have", "C. are", "D. were"],
        "answer": "A",
        "explain": "all指事情（不可数）时谓语用单数；此处为被动完成has been done。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "不定代词",
        "variant": "二者之间的选择应答",
        "kind": "choice",
        "stem": "—Which of the two shirts would you like to take? —______. They don't fit me at all.",
        "options": ["A. Neither", "B. Either", "C. None", "D. Both"],
        "answer": "A",
        "explain": "两者都不用neither；none用于三者以上；由don't fit可知两件都不要。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "不定代词",
        "variant": "either与名词单数搭配",
        "kind": "choice",
        "stem": "There are tall trees on ______ side of the country road.",
        "options": ["A. either", "B. both", "C. all", "D. every"],
        "answer": "A",
        "explain": "side为单数名词，表示\"（路两边的）每一边\"用either side；both后须接复数名词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "不定代词",
        "variant": "each的用法",
        "kind": "fill",
        "stem": "______ (每个) of the students was given a new dictionary on Teachers' Day.",
        "options": [],
        "answer": "each",
        "explain": "each of+复数名词作主语时谓语用单数，本句was given用单数，故填each。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "不定代词",
        "variant": "二者之间的选择应答",
        "kind": "choice",
        "stem": "—Which of these two English books will you take? —I'll take ______, one for my sister and the other for myself.",
        "options": ["A. both", "B. either", "C. neither", "D. none"],
        "answer": "A",
        "explain": "由one...the other可知两本都要，用both；either/neither只指一个，none用于三者以上。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "不定代词",
        "variant": "both/neither/all/none与主谓一致",
        "kind": "fill",
        "stem": "______ (两者都不) of the answers is correct, so I have to work out the problem again.",
        "options": [],
        "answer": "neither",
        "explain": "两者都不用neither；谓语is为单数，与neither of搭配一致。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    # ================= 指代词辨析 =================
    {
        "node": "指代词辨析",
        "variant": "one泛指同类事物",
        "kind": "choice",
        "stem": "I'm looking for a house in the countryside. I'd like ______ with a big garden.",
        "options": ["A. one", "B. it", "C. that", "D. this"],
        "answer": "A",
        "explain": "one泛指与前面名词同类但非同一个的事物；it特指上文提到的那一个。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "指代词辨析",
        "variant": "that/those用于比较结构",
        "kind": "choice",
        "stem": "The weather in Beijing is much colder than ______ in Guangzhou in winter.",
        "options": ["A. that", "B. it", "C. one", "D. this"],
        "answer": "A",
        "explain": "that代替前面提到的不可数名词weather，构成the weather...than that in...的比较结构。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "指代词辨析",
        "variant": "that/those用于比较结构",
        "kind": "choice",
        "stem": "The apples on the table are much bigger than ______ in the basket.",
        "options": ["A. those", "B. that", "C. one", "D. it"],
        "answer": "A",
        "explain": "those代替前面的复数名词apples，与in the basket构成比较；that只替代单数或不可数名词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "指代词辨析",
        "variant": "it的特指与形式用法",
        "kind": "choice",
        "stem": "—Have you found your lost pen? —Yes, I found ______ under the bed this morning.",
        "options": ["A. it", "B. one", "C. that", "D. this"],
        "answer": "A",
        "explain": "it特指上文提到的那支丢失的钢笔，即找到的正是原来的那支。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "指代词辨析",
        "variant": "that/those用于比较结构",
        "kind": "fill",
        "stem": "The population of China is much larger than ______ (用恰当的指代词) of Japan.",
        "options": [],
        "answer": "that",
        "explain": "that代替前面单数名词population，构成population...than that of...的比较结构。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "指代词辨析",
        "variant": "it的特指与形式用法",
        "kind": "fill",
        "stem": "______ (用it开头填空) is no use crying over spilt milk.",
        "options": [],
        "answer": "it",
        "explain": "it作形式主语，真正的主语是后面的动名词短语crying over spilt milk。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "指代词辨析",
        "variant": "it的特指与形式用法",
        "kind": "choice",
        "stem": "He found ______ hard to get along with his new classmate at first.",
        "options": ["A. it", "B. that", "C. this", "D. one"],
        "answer": "A",
        "explain": "it作形式宾语，代替真正的宾语不定式to get along with...，构成find it+adj.+to do结构。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "指代词辨析",
        "variant": "one泛指同类事物",
        "kind": "choice",
        "stem": "The new bridge over the river is more beautiful than the old ______.",
        "options": ["A. one", "B. it", "C. that", "D. this"],
        "answer": "A",
        "explain": "one代替同类事物bridge，指另一座桥；it则指同一座桥，不合逻辑。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    # ================= 倍数表达法 =================
    {
        "node": "倍数表达法",
        "variant": "倍数+比较级+than",
        "kind": "choice",
        "stem": "This newly built hall is ______ the old one.",
        "options": ["A. three times larger than", "B. as three times large as", "C. three times as larger as", "D. larger three times than"],
        "answer": "A",
        "explain": "倍数+比较级+than为固定倍数表达法，即three times larger than；B、C、D语序或形式错误。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倍数表达法",
        "variant": "倍数+as...as",
        "kind": "choice",
        "stem": "The new library is ______ the old one, so it can hold far more readers.",
        "options": ["A. twice as big as", "B. twice bigger as", "C. as twice big as", "D. two times as bigger as"],
        "answer": "A",
        "explain": "倍数+as+原级+as为固定结构，twice as big as意为\"是……的两倍大\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倍数表达法",
        "variant": "倍数+as...as",
        "kind": "choice",
        "stem": "He paid ______ for the new coat as I paid for my shoes.",
        "options": ["A. twice as much", "B. twice as many", "C. as twice much", "D. twice more"],
        "answer": "A",
        "explain": "钱为不可数概念用much，倍数置于as...as之前，即twice as much...as。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倍数表达法",
        "variant": "倍数+as...as",
        "kind": "fill",
        "stem": "This road is ______ (两倍) as long as that one.",
        "options": [],
        "answer": "twice",
        "explain": "倍数+as...as结构中，倍数词twice放在as...as之前。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倍数表达法",
        "variant": "倍数+the+名词+of",
        "kind": "choice",
        "stem": "Our new classroom is ______ the old one.",
        "options": ["A. twice the size of", "B. twice the size than", "C. the twice size of", "D. twice sizes of"],
        "answer": "A",
        "explain": "倍数+the+名词+of为固定表达，twice the size of意为\"是……的两倍大小\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倍数表达法",
        "variant": "倍数+the+名词+of",
        "kind": "choice",
        "stem": "The earth is ______ the moon, though they both go around the sun.",
        "options": ["A. forty-nine times the size of", "B. forty-nine times size of", "C. forty-nine times the size than", "D. the forty-nine times size of"],
        "answer": "A",
        "explain": "倍数+the size of为固定结构，the前不可再加the，也不能用than替换of。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倍数表达法",
        "variant": "倍数+that of结构",
        "kind": "choice",
        "stem": "The output of rice in this village this year is twice ______ of last year.",
        "options": ["A. that", "B. it", "C. this", "D. those"],
        "answer": "A",
        "explain": "that代替前面不可数名词output，构成twice that of last year的比较结构。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倍数表达法",
        "variant": "倍数+比较级+than",
        "kind": "fill",
        "stem": "This tall tree is ______ (三倍) taller than that one.",
        "options": [],
        "answer": "three times",
        "explain": "倍数+比较级+than结构中，倍数短语three times放在比较级taller之前。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= so与such的区别 =================
    {
        "node": "so与such的区别",
        "variant": "such+名词短语",
        "kind": "choice",
        "stem": "It was ______ exciting news that all of us jumped with joy at once.",
        "options": ["A. such", "B. so", "C. such a", "D. so a"],
        "answer": "A",
        "explain": "news为不可数名词，用such+形容词+名词，不加冠词a；so后接形容词或副词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "so与such的区别",
        "variant": "so+形容词/副词",
        "kind": "choice",
        "stem": "The problem was ______ difficult that nobody in our class could work it out.",
        "options": ["A. so", "B. such", "C. such a", "D. very"],
        "answer": "A",
        "explain": "so+形容词/副词+that从句；difficult是形容词且其后无名词，用so。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "so与such的区别",
        "variant": "so+形容词+a/an+名词",
        "kind": "choice",
        "stem": "He is ______ honest a man that we all like to make friends with him.",
        "options": ["A. so", "B. such", "C. such an", "D. so an"],
        "answer": "A",
        "explain": "so+形容词+a/an+单数名词+that为固定语序；such用于形容词之前，即such an honest man。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "so与such的区别",
        "variant": "such+名词短语",
        "kind": "choice",
        "stem": "It was ______ fine weather that we decided to go for a picnic by the lake.",
        "options": ["A. such", "B. so", "C. such a", "D. so a"],
        "answer": "A",
        "explain": "weather为不可数名词，用such+形容词+名词+that结构，不加冠词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "so与such的区别",
        "variant": "so many/much/few/little",
        "kind": "choice",
        "stem": "There were ______ people in the square that we could hardly move a step.",
        "options": ["A. so many", "B. so much", "C. such many", "D. such much"],
        "answer": "A",
        "explain": "people为复数可数名词，用so many；much修饰不可数名词；such不与many/much直接连用。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "so与such的区别",
        "variant": "such+名词短语",
        "kind": "choice",
        "stem": "I've made ______ progress this term that my teacher praised me in class.",
        "options": ["A. such", "B. so", "C. so much a", "D. such a"],
        "answer": "A",
        "explain": "progress为不可数名词，用such+形容词+名词+that结构，不加冠词a。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "so与such的区别",
        "variant": "so+形容词/副词",
        "kind": "fill",
        "stem": "The box is ______ (如此重) that I can't lift it onto the desk.",
        "options": [],
        "answer": "so heavy",
        "explain": "so+形容词+that从句，\"如此重\"译为so heavy。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "so与such的区别",
        "variant": "such+名词短语",
        "kind": "fill",
        "stem": "They are ______ (如此有趣的故事) that children love reading them again and again.",
        "options": [],
        "answer": "such interesting stories",
        "explain": "stories为复数名词，用such+形容词+复数名词+that结构。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    # ================= 易混动词辨析 =================
    {
        "node": "易混动词辨析",
        "variant": "接续搭配",
        "kind": "choice",
        "stem": "After many attempts, she finally ______ in solving this difficult maths problem.",
        "options": ["A. succeeded", "B. managed", "C. attempted", "D. insisted"],
        "answer": "A",
        "explain": "succeed in doing意为\"成功做成某事\"；managed后接to do；attempted后接to do；insisted后接on doing。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混动词辨析",
        "variant": "接续搭配",
        "kind": "choice",
        "stem": "The head teacher suggested ______ the sports meeting until the weather cleared up.",
        "options": ["A. putting off", "B. to put off", "C. to putting off", "D. put off"],
        "answer": "A",
        "explain": "suggest后接动名词作宾语，不接不定式，即suggest doing sth。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混动词辨析",
        "variant": "接续搭配",
        "kind": "fill",
        "stem": "Would you mind ______ (用close的适当形式) the window? It's a bit cold in here.",
        "options": [],
        "answer": "closing",
        "explain": "mind后接动名词作宾语，即mind doing sth，故填closing。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混动词辨析",
        "variant": "近义动词辨析",
        "kind": "choice",
        "stem": "He was ______ a medal for saving the drowning child in the icy river.",
        "options": ["A. awarded", "B. won", "C. praised", "D. thanked"],
        "answer": "A",
        "explain": "award sb sth意为\"授予某人某物\"，被动为be awarded a medal；win后接奖但用主动；praise/thank不接medal。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混动词辨析",
        "variant": "近义动词辨析",
        "kind": "choice",
        "stem": "He ______ the early train, so he had to wait two hours for the next one.",
        "options": ["A. missed", "B. lost", "C. caught", "D. followed"],
        "answer": "A",
        "explain": "miss the train意为\"错过火车\"；lose意为\"丢失\"；caught与had to wait矛盾。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混动词辨析",
        "variant": "接续搭配",
        "kind": "choice",
        "stem": "The English teacher asked us to pay attention ______ our pronunciation in oral practice.",
        "options": ["A. to", "B. on", "C. at", "D. in"],
        "answer": "A",
        "explain": "pay attention to为固定搭配，意为\"注意……\"，to为介词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混动词辨析",
        "variant": "不及物动词不能用于被动",
        "kind": "choice",
        "stem": "The Second World War ______ in 1939 and ______ for six years.",
        "options": ["A. broke out; lasted", "B. was broken out; lasted", "C. broke out; was lasted", "D. was broken out; was lasted"],
        "answer": "A",
        "explain": "break out（爆发）和last（持续）都是不及物动词短语，不能用于被动语态。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混动词辨析",
        "variant": "不及物动词不能用于被动",
        "kind": "fill",
        "stem": "He ______ (用rise或raise的适当形式) his hand to ask the teacher a question.",
        "options": [],
        "answer": "raised",
        "explain": "raise为及物动词，意为\"举起\"，后接宾语his hand；rise是不及物动词，不能接宾语。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    # ================= 固定搭配辨析 =================
    {
        "node": "固定搭配辨析",
        "variant": "动词固定搭配",
        "kind": "choice",
        "stem": "The doctor advised him ______ smoking and take more exercise to keep healthy.",
        "options": ["A. to give up", "B. giving up", "C. give up", "D. gave up"],
        "answer": "A",
        "explain": "advise sb to do sth为固定搭配，意为\"建议某人做某事\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "固定搭配辨析",
        "variant": "动词固定搭配",
        "kind": "choice",
        "stem": "I'm looking forward to ______ from you as soon as possible.",
        "options": ["A. hearing", "B. hear", "C. heard", "D. be heard"],
        "answer": "A",
        "explain": "look forward to中to为介词，后接动名词，即look forward to doing sth。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "固定搭配辨析",
        "variant": "介词固定搭配",
        "kind": "choice",
        "stem": "______ the help of my English teacher, I made great progress last term.",
        "options": ["A. With", "B. Under", "C. In", "D. By"],
        "answer": "A",
        "explain": "with the help of为固定搭配，意为\"在……的帮助下\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "固定搭配辨析",
        "variant": "介词固定搭配",
        "kind": "choice",
        "stem": "To our ______, the famous scientist came to give us a lecture in person.",
        "options": ["A. surprise", "B. surprised", "C. surprising", "D. surprises"],
        "answer": "A",
        "explain": "to one's surprise为固定搭配，意为\"令某人惊讶的是\"，surprise为名词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "固定搭配辨析",
        "variant": "形容词与介词搭配",
        "kind": "fill",
        "stem": "My mother is always busy ______ (用介词) housework on weekends.",
        "options": [],
        "answer": "with",
        "explain": "be busy with sth为固定搭配，意为\"忙于某事\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "固定搭配辨析",
        "variant": "形容词与介词搭配",
        "kind": "choice",
        "stem": "After living in the city for years, he is still not used ______ the quiet life in the countryside.",
        "options": ["A. to", "B. for", "C. with", "D. at"],
        "answer": "A",
        "explain": "be used to sth为固定搭配，意为\"习惯于……\"，此处to为介词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "固定搭配辨析",
        "variant": "名词类固定搭配",
        "kind": "choice",
        "stem": "As a League member, he takes an active part ______ all kinds of school activities.",
        "options": ["A. in", "B. at", "C. on", "D. for"],
        "answer": "A",
        "explain": "take an active part in为固定搭配，意为\"积极参加……\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "固定搭配辨析",
        "variant": "介词固定搭配",
        "kind": "fill",
        "stem": "She prefers reading books ______ (用介词) watching TV in her free time.",
        "options": [],
        "answer": "to",
        "explain": "prefer doing A to doing B为固定搭配，意为\"宁愿做A而不愿做B\"，to为介词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    # ================= 短语动词 =================
    {
        "node": "短语动词",
        "variant": "动词相同介词或副词不同",
        "kind": "choice",
        "stem": "He ______ the company's offer because the pay was far too low.",
        "options": ["A. turned down", "B. turned on", "C. turned up", "D. turned in"],
        "answer": "A",
        "explain": "turn down意为\"拒绝\"；turn on打开；turn up出现、调大；turn in上交。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "短语动词",
        "variant": "动词相同介词或副词不同",
        "kind": "choice",
        "stem": "Don't forget to ______ the lights when you leave the classroom in the evening.",
        "options": ["A. turn off", "B. turn on", "C. turn up", "D. turn down"],
        "answer": "A",
        "explain": "离开教室应关灯，turn off意为\"关掉\"；turn on打开；turn up调大。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "短语动词",
        "variant": "动词相同介词或副词不同",
        "kind": "choice",
        "stem": "I couldn't ______ what he was saying on the phone because of the loud noise outside.",
        "options": ["A. make out", "B. make up", "C. make for", "D. make into"],
        "answer": "A",
        "explain": "make out意为\"辨认出、听清\"；make up编造、组成；make for走向。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "短语动词",
        "variant": "动词相同介词或副词不同",
        "kind": "choice",
        "stem": "After a heated discussion, the group finally ______ a practical plan for the project.",
        "options": ["A. came up with", "B. came up to", "C. came along with", "D. came out of"],
        "answer": "A",
        "explain": "come up with意为\"想出、提出（主意、计划）\"；其余选项无此义。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "短语动词",
        "variant": "动词+介词搭配",
        "kind": "fill",
        "stem": "It took him almost a month to get ______ (痊愈，用介词) his serious illness.",
        "options": [],
        "answer": "over",
        "explain": "get over意为\"克服、从（疾病）中恢复\"，get over his illness即痊愈。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "短语动词",
        "variant": "三词短语动词",
        "kind": "choice",
        "stem": "I really can't put up ______ the noise from the next room any longer.",
        "options": ["A. with", "B. to", "C. for", "D. at"],
        "answer": "A",
        "explain": "put up with为三词短语动词，意为\"忍受\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "短语动词",
        "variant": "三词短语动词",
        "kind": "choice",
        "stem": "Please keep an eye ______ my suitcase while I go to buy the tickets.",
        "options": ["A. on", "B. at", "C. in", "D. to"],
        "answer": "A",
        "explain": "keep an eye on为固定短语，意为\"照看、留意\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "短语动词",
        "variant": "动词+介词搭配",
        "kind": "fill",
        "stem": "The sports meeting has been ______ (推迟，用put构成的短语) until next month because of the rain.",
        "options": [],
        "answer": "put off",
        "explain": "put off意为\"推迟\"，与until next month搭配符合句意。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 易混名词辨析 =================
    {
        "node": "易混名词辨析",
        "variant": "形近名词辨析",
        "kind": "choice",
        "stem": "Before you take the medicine, read the ______ on the bottle carefully.",
        "options": ["A. instructions", "B. introductions", "C. productions", "D. instructions on it"],
        "answer": "A",
        "explain": "instructions意为\"说明书、用法说明\"，常与药瓶搭配；introductions介绍；productions产品。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混名词辨析",
        "variant": "近义名词辨析",
        "kind": "choice",
        "stem": "He gave me a lot of ______ on how to improve my spoken English.",
        "options": ["A. advice", "B. advices", "C. suggestion", "D. informations"],
        "answer": "A",
        "explain": "advice为不可数名词，无复数形式；suggestion可数但需用复数或加冠词；information不可数。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混名词辨析",
        "variant": "形近名词辨析",
        "kind": "choice",
        "stem": "The ______ between the two villages is about ten kilometres, so it takes an hour to walk there.",
        "options": ["A. distance", "B. distant", "C. difference", "D. different"],
        "answer": "A",
        "explain": "distance为名词，意为\"距离\"；distant是形容词；difference意为\"不同\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混名词辨析",
        "variant": "单复数与不可数",
        "kind": "choice",
        "stem": "Please accept my sincere ______ on your winning the first prize in the contest.",
        "options": ["A. congratulations", "B. congratulation", "C. celebrate", "D. celebration"],
        "answer": "A",
        "explain": "表示祝贺常用复数形式congratulations；celebrate为动词；celebration指庆祝活动。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混名词辨析",
        "variant": "单复数与不可数",
        "kind": "choice",
        "stem": "—Would you like some more ______? —No, thanks. I'm quite full already.",
        "options": ["A. chicken", "B. chickens", "C. a chicken", "D. the chicken"],
        "answer": "A",
        "explain": "chicken作\"鸡肉\"讲时为不可数名词；chickens指小鸡；some后不加冠词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混名词辨析",
        "variant": "近义名词辨析",
        "kind": "choice",
        "stem": "He gets a good ______ as an engineer in the factory, about 10,000 yuan a month.",
        "options": ["A. salary", "B. wage", "C. fee", "D. bill"],
        "answer": "A",
        "explain": "salary指按月发放的工资；wage多指按周或日计的工资；fee指服务费；bill指账单。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混名词辨析",
        "variant": "单复数与不可数",
        "kind": "fill",
        "stem": "Thanks to the Internet, we can get lots of ______ (信息) quickly and easily.",
        "options": [],
        "answer": "information",
        "explain": "information为不可数名词，没有复数形式，lots of后接原形。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混名词辨析",
        "variant": "语境词义辨析",
        "kind": "fill",
        "stem": "—What's the ______ (天气) like today in your hometown? —It's sunny and warm.",
        "options": [],
        "answer": "weather",
        "explain": "询问天气用What's the weather like...?，weather为不可数名词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    # ================= 易混形容词副词辨析 =================
    {
        "node": "易混形容词副词辨析",
        "variant": "实义与抽象意义副词",
        "kind": "choice",
        "stem": "The plane flew ______ above the clouds until it disappeared from view.",
        "options": ["A. high", "B. highly", "C. taller", "D. more highly"],
        "answer": "A",
        "explain": "表示实际高度高用high；highly表示抽象的\"高度地\"，如think highly of。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混形容词副词辨析",
        "variant": "实义与抽象意义副词",
        "kind": "choice",
        "stem": "Mr Smith is a patient teacher and is ______ respected by all his students.",
        "options": ["A. highly", "B. high", "C. taller", "D. higher"],
        "answer": "A",
        "explain": "highly respected为固定表达，表示抽象程度\"非常、高度地\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混形容词副词辨析",
        "variant": "形近副词辨析",
        "kind": "choice",
        "stem": "We must do something to protect the environment; ______, our life will be in great danger.",
        "options": ["A. otherwise", "B. other", "C. others", "D. another"],
        "answer": "A",
        "explain": "otherwise为副词，意为\"否则、要不然\"，表示相反的条件；其余为代词或形容词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混形容词副词辨析",
        "variant": "形近副词辨析",
        "kind": "choice",
        "stem": "It's ______ nine o'clock and the concert will begin, so we must start at once.",
        "options": ["A. already", "B. yet", "C. still", "D. ready"],
        "answer": "A",
        "explain": "already意为\"已经\"，用于肯定句；yet用于否定句和疑问句；still意为\"仍然\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混形容词副词辨析",
        "variant": "-ing与-ed形容词",
        "kind": "choice",
        "stem": "The problem is really ______; we are all ______ about how to solve it.",
        "options": ["A. worrying; worried", "B. worried; worrying", "C. worry; worried", "D. worrying; worrying"],
        "answer": "A",
        "explain": "问题本身令人担忧用worrying；人感到担忧用worried，即be worried about。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混形容词副词辨析",
        "variant": "-ing与-ed形容词",
        "kind": "choice",
        "stem": "The crowd watched the winner ______, and there was a(an) ______ smile on every face.",
        "options": ["A. admiringly; admiring", "B. admiring; admiringly", "C. admired; admiring", "D. admiringly; admired"],
        "answer": "A",
        "explain": "修饰动词watched用副词admiringly；修饰名词smile用形容词admiring。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混形容词副词辨析",
        "variant": "lonely与alone",
        "kind": "fill",
        "stem": "The old man lives in a quiet village, but he never feels ______ (孤独的) because his children often visit him.",
        "options": [],
        "answer": "lonely",
        "explain": "lonely表示主观上\"孤独的\"；alone只表示客观上\"独自一人\"，不含感情色彩。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "易混形容词副词辨析",
        "variant": "实义与抽象意义副词",
        "kind": "fill",
        "stem": "The goalkeeper jumped ______ (高高地，用high或highly中正确的词) to catch the ball.",
        "options": [],
        "answer": "high",
        "explain": "表示实际的高度用high；highly表示抽象程度，此处为具体动作的高度。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    # ================= 近义词辨析 =================
    {
        "node": "近义词辨析",
        "variant": "动词近义辨析",
        "kind": "choice",
        "stem": "The speaker ______ his voice so that everyone at the back could hear him clearly.",
        "options": ["A. raised", "B. rose", "C. rose up", "D. arose"],
        "answer": "A",
        "explain": "raise为及物动词，意为\"提高\"，后接宾语his voice；rise/arise为不及物动词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "近义词辨析",
        "variant": "动词近义辨析",
        "kind": "choice",
        "stem": "Please ______ me a favor and pass the salt to me over the table.",
        "options": ["A. do", "B. make", "C. give", "D. take"],
        "answer": "A",
        "explain": "do sb a favor为固定搭配，意为\"帮某人一个忙\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "近义词辨析",
        "variant": "名词近义辨析",
        "kind": "choice",
        "stem": "After a year of hard work, he made rapid ______ in English and passed the exam easily.",
        "options": ["A. progress", "B. programme", "C. project", "D. promise"],
        "answer": "A",
        "explain": "make progress为固定搭配，意为\"取得进步\"；progress不可数，不加冠词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "近义词辨析",
        "variant": "名词近义辨析",
        "kind": "choice",
        "stem": "Columbus' ______ of the New World in 1492 changed the history of the world.",
        "options": ["A. discovery", "B. invention", "C. creation", "D. imagination"],
        "answer": "A",
        "explain": "discovery指发现原本就存在的事物；invention指发明原本不存在的东西。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "近义词辨析",
        "variant": "形容词近义辨析",
        "kind": "choice",
        "stem": "The weather in Kunming is ______ all year round, neither too hot nor too cold.",
        "options": ["A. pleasant", "B. pleased", "C. pleasure", "D. unpleasant"],
        "answer": "A",
        "explain": "pleasant意为\"令人舒适的\"，修饰天气；pleased修饰人；unpleasant与语境矛盾。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "近义词辨析",
        "variant": "形容词近义辨析",
        "kind": "choice",
        "stem": "He felt ______ when he heard that he had been admitted to his dream university.",
        "options": ["A. excited", "B. exciting", "C. excitement", "D. excite"],
        "answer": "A",
        "explain": "修饰人表示\"感到兴奋的\"用excited；exciting修饰事物；excitement为名词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "近义词辨析",
        "variant": "副词近义辨析",
        "kind": "fill",
        "stem": "She has practiced speaking English every day, so she speaks it very ______ (用fluent的正确形式).",
        "options": [],
        "answer": "fluently",
        "explain": "修饰动词speaks用副词，fluent的副词形式为fluently。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "近义词辨析",
        "variant": "动词近义辨析",
        "kind": "fill",
        "stem": "May I ______ (用borrow或lend的正确形式) your dictionary for a while? Mine is lost.",
        "options": [],
        "answer": "borrow",
        "explain": "borrow指\"借入\"， borrow sth from sb；lend指\"借出\"，此处指借入对方的词典。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    # ================= 词性转换（派生法） =================
    {
        "node": "词性转换（派生法）",
        "variant": "-tion/-ment名词后缀",
        "kind": "choice",
        "stem": "The ______ of the computer has greatly changed the way people work and live.",
        "options": ["A. invention", "B. invent", "C. inventive", "D. inventor"],
        "answer": "A",
        "explain": "定冠词The后接名词，invent的名词形式为invention，意为\"发明\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "词性转换（派生法）",
        "variant": "-tion/-ment名词后缀",
        "kind": "choice",
        "stem": "To our ______, he passed the driving test without any practice before it.",
        "options": ["A. amazement", "B. amaze", "C. amazing", "D. amazed"],
        "answer": "A",
        "explain": "to one's+名词表\"令某人……的是\"，amaze的名词形式为amazement。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "词性转换（派生法）",
        "variant": "-tion/-ment名词后缀",
        "kind": "fill",
        "stem": "He hesitated for a while, and then made a quick ______ (用decide的正确形式) to go abroad.",
        "options": [],
        "answer": "decision",
        "explain": "形容词quick后接名词，decide的名词形式为decision，make a decision意为\"做决定\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "词性转换（派生法）",
        "variant": "-ful/-ous形容词后缀",
        "kind": "choice",
        "stem": "It is ______ to swim in this river alone, because the water runs very fast.",
        "options": ["A. dangerous", "B. danger", "C. dangerously", "D. endanger"],
        "answer": "A",
        "explain": "It is+形容词+to do结构，danger的形容词形式为dangerous。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "词性转换（派生法）",
        "variant": "-ful/-ous形容词后缀",
        "kind": "choice",
        "stem": "She always wears a ______ smile and is ready to help anyone in trouble.",
        "options": ["A. friendly", "B. friend", "C. friendship", "D. friendlily"],
        "answer": "A",
        "explain": "修饰名词smile用形容词，friend+ly构成形容词friendly。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "词性转换（派生法）",
        "variant": "否定前缀",
        "kind": "choice",
        "stem": "He was ______ to pass the exam because he had spent all his time playing games.",
        "options": ["A. unable", "B. able", "C. ability", "D. disable"],
        "answer": "A",
        "explain": "由because从句可知他没能通过考试，be unable to do意为\"不能做某事\"。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "词性转换（派生法）",
        "variant": "否定前缀",
        "kind": "fill",
        "stem": "It's ______ (用possible的正确形式，加前缀) to finish such heavy work in one day.",
        "options": [],
        "answer": "impossible",
        "explain": "由句意可知一天完成是不可能的，possible加否定前缀im-构成impossible。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "词性转换（派生法）",
        "variant": "词性判断",
        "kind": "choice",
        "stem": "The ______ boy answered all the difficult questions correctly in the quiz show.",
        "options": ["A. clever", "B. cleverly", "C. cleverness", "D. cleverer"],
        "answer": "A",
        "explain": "修饰名词boy用形容词clever；cleverly为副词；cleverness为名词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
]
