# 用途：高考英语知识点练习题库 A 组（16 个知识点 × 8 题 = 128 题），AI 机器生成，未人工复核。
# node 必须与知识点清单 id 完全一致；fill 答案为小写英文；choice 答案为大写字母。

QUESTIONS = [
    # ================= 非谓语动词 =================
    {
        "node": "非谓语动词",
        "variant": "不定式",
        "kind": "choice",
        "stem": "Tom was the first student ______ at the meeting yesterday.",
        "options": ["A. to speak", "B. speaking", "C. spoke", "D. speaks"],
        "answer": "A",
        "explain": "名词被序数词the first修饰时后接不定式作定语；speaking表主动进行不合此结构。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "非谓语动词",
        "variant": "不定式",
        "kind": "fill",
        "stem": "The government has taken effective measures ______ (protect) the wetland.",
        "options": [],
        "answer": "to protect",
        "explain": "采取措施的目的是保护湿地，用不定式to protect作目的状语。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "非谓语动词",
        "variant": "动名词",
        "kind": "choice",
        "stem": "It's no use ______ him now; he is having a class.",
        "options": ["A. to phone", "B. phoning", "C. phone", "D. phoned"],
        "answer": "B",
        "explain": "It's no use doing sth.为固定句型，用动名词；to phone不符合该句型。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "非谓语动词",
        "variant": "动名词",
        "kind": "fill",
        "stem": "She is used to ______ (get) up early to read English aloud.",
        "options": [],
        "answer": "getting",
        "explain": "be used to中的to是介词，后接动名词getting；don't confuse with used to do。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "非谓语动词",
        "variant": "现在分词",
        "kind": "choice",
        "stem": "______ his address, I had to ask a passer-by for help.",
        "options": ["A. Not knowing", "B. Not known", "C. Not to know", "D. Knowing not"],
        "answer": "A",
        "explain": "I与know是主动关系且原因先发生，用现在分词否定式Not knowing；not须置于非谓语之前。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "非谓语动词",
        "variant": "现在分词",
        "kind": "fill",
        "stem": "The man ______ (stand) at the gate is our new headmaster.",
        "options": [],
        "answer": "standing",
        "explain": "the man与stand是主动且正在进行的关系，用现在分词standing作后置定语。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "非谓语动词",
        "variant": "过去分词",
        "kind": "choice",
        "stem": "The new library, ______ last month, has attracted many students.",
        "options": ["A. opened", "B. opening", "C. to open", "D. opens"],
        "answer": "A",
        "explain": "library与open是被动关系且已完成，用过去分词opened作非限制性定语；opening表主动错误。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "非谓语动词",
        "variant": "过去分词",
        "kind": "fill",
        "stem": "Our school has far more club activities ______ (compare) with last year.",
        "options": [],
        "answer": "compared",
        "explain": "compared with...为固定表达，与……相比，逻辑主语school与compare是被动关系。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 定语从句 =================
    {
        "node": "定语从句",
        "variant": "关系代词",
        "kind": "choice",
        "stem": "A true friend is someone ______ accepts you as you are.",
        "options": ["A. who", "B. whom", "C. which", "D. whose"],
        "answer": "A",
        "explain": "先行词someone指人且在从句中作主语，用who；whom只能作宾语。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句",
        "variant": "关系代词",
        "kind": "fill",
        "stem": "Li Ming is the boy ______ father works in a hospital nearby.",
        "options": [],
        "answer": "whose",
        "explain": "从句中缺少定语（……的父亲），先行词是人，用whose表示所属关系。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句",
        "variant": "关系副词",
        "kind": "choice",
        "stem": "I still remember the days ______ we studied together in the countryside.",
        "options": ["A. when", "B. which", "C. that", "D. where"],
        "answer": "A",
        "explain": "先行词the days表时间且从句结构完整，用关系副词when；where指地点不符。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句",
        "variant": "关系副词",
        "kind": "fill",
        "stem": "This is the school ______ my mother taught English for twenty years.",
        "options": [],
        "answer": "where",
        "explain": "先行词the school在从句中作地点状语（taught in the school），用关系副词where。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句",
        "variant": "介词+关系代词",
        "kind": "choice",
        "stem": "This is the pen ______ I wrote the letter.",
        "options": ["A. with which", "B. with that", "C. by which", "D. in which"],
        "answer": "A",
        "explain": "write with a pen表工具，介词with提前后只搭配which，that不能紧跟介词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句",
        "variant": "介词+关系代词",
        "kind": "fill",
        "stem": "Mr. Smith is the person from ______ I borrowed the dictionary.",
        "options": [],
        "answer": "whom",
        "explain": "介词from后指人的关系代词只能用whom，不能用who或that。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句",
        "variant": "非限制性",
        "kind": "choice",
        "stem": "He passed the driving test, ______ made his parents very happy.",
        "options": ["A. which", "B. that", "C. what", "D. it"],
        "answer": "A",
        "explain": "非限制性定语从句指代前面整件事，用which；that不能引导非限制性定语从句。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "定语从句",
        "variant": "非限制性",
        "kind": "fill",
        "stem": "We visited the Great Wall, ______ is one of the wonders of the world.",
        "options": [],
        "answer": "which",
        "explain": "非限制性定语从句中作主语只能用which；that不用于非限制性定语从句。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 名词性从句 =================
    {
        "node": "名词性从句",
        "variant": "主语从句",
        "kind": "choice",
        "stem": "______ the meeting will be held hasn't been decided yet.",
        "options": ["A. That", "B. Whether", "C. What", "D. Which"],
        "answer": "B",
        "explain": "主语从句位于句首表'是否'只能用Whether；That无词义不合逻辑，What需在从句中作成分。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词性从句",
        "variant": "主语从句",
        "kind": "fill",
        "stem": "It is still unknown ______ will take part in the competition.",
        "options": [],
        "answer": "who",
        "explain": "主语从句中缺少主语且指人表'谁'，用who引导；连接词须在从句中作主语。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词性从句",
        "variant": "宾语从句",
        "kind": "choice",
        "stem": "I wonder ______ or not the plan is practical.",
        "options": ["A. if", "B. whether", "C. that", "D. what"],
        "answer": "B",
        "explain": "与or not连用表'是否'只能用whether；if不能直接与or not连用。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词性从句",
        "variant": "宾语从句",
        "kind": "fill",
        "stem": "Could you tell me ______ the nearest bank is?",
        "options": [],
        "answer": "where",
        "explain": "宾语从句表'在哪里'且从句中缺地点状语，用where引导。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词性从句",
        "variant": "表语从句",
        "kind": "choice",
        "stem": "The reason for his absence was ______ he was ill.",
        "options": ["A. because", "B. that", "C. why", "D. what"],
        "answer": "B",
        "explain": "The reason...was that...为固定搭配；because与reason语义重复，why表结果不合逻辑。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词性从句",
        "variant": "表语从句",
        "kind": "fill",
        "stem": "The question is ______ we can finish the work on time.",
        "options": [],
        "answer": "whether",
        "explain": "表语从句表'是否'只能用whether；if不能引导表语从句。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词性从句",
        "variant": "同位语从句",
        "kind": "choice",
        "stem": "The news ______ our team won the match excited us all.",
        "options": ["A. which", "B. that", "C. what", "D. when"],
        "answer": "B",
        "explain": "that引导同位语从句解释news的内容且在从句中不作成分；which引导定语从句需作成分。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "名词性从句",
        "variant": "同位语从句",
        "kind": "fill",
        "stem": "The news spread quickly ______ the famous singer would come to our city.",
        "options": [],
        "answer": "that",
        "explain": "that引导同位语从句补充说明news的具体内容，在从句中不作任何成分。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 状语从句 =================
    {
        "node": "状语从句",
        "variant": "时间状语从句",
        "kind": "choice",
        "stem": "I was reading in the library ______ the lights suddenly went out.",
        "options": ["A. while", "B. when", "C. as", "D. since"],
        "answer": "B",
        "explain": "be doing...when...表示'正在……这时突然'，为固定句型；while从句须用延续性动作。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "状语从句",
        "variant": "时间状语从句",
        "kind": "fill",
        "stem": "It will be two years ______ we meet again.",
        "options": [],
        "answer": "before",
        "explain": "It will be+时间段+before...表示'要过……才'，为固定句型。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "状语从句",
        "variant": "条件状语从句",
        "kind": "choice",
        "stem": "You will succeed in the end ______ you don't give up halfway.",
        "options": ["A. as long as", "B. even if", "C. in case", "D. now that"],
        "answer": "A",
        "explain": "as long as表'只要'引导条件；even if表让步与语义矛盾，now that表原因。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "状语从句",
        "variant": "条件状语从句",
        "kind": "fill",
        "stem": "We'll go hiking tomorrow ______ it rains.",
        "options": [],
        "answer": "unless",
        "explain": "unless=if...not，表示'除非'，引导否定条件；主句用将来时从句用一般现在时。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "状语从句",
        "variant": "让步状语从句",
        "kind": "choice",
        "stem": "______ hard he tried, he couldn't work out the maths problem.",
        "options": ["A. However", "B. Whatever", "C. Though", "D. Even"],
        "answer": "A",
        "explain": "However+形容词/副词+主谓表'无论多么'；hard是副词，Whatever不能修饰hard。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "状语从句",
        "variant": "让步状语从句",
        "kind": "fill",
        "stem": "Young ______ he is, he has rich experience in teaching.",
        "options": [],
        "answer": "as",
        "explain": "形容词提前构成as引导的让步倒装：Young as he is=Though he is young。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "状语从句",
        "variant": "原因状语从句",
        "kind": "choice",
        "stem": "______ you have finished your work, you may go home now.",
        "options": ["A. Now that", "B. Even though", "C. As soon as", "D. In case"],
        "answer": "A",
        "explain": "Now that表'既然'引导原因状语从句；Even though表让步，In case表条件。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "状语从句",
        "variant": "原因状语从句",
        "kind": "fill",
        "stem": "I stayed at home ______ it was raining hard.",
        "options": [],
        "answer": "because",
        "explain": "下雨是待在家里的直接原因，用because引导原因状语从句语气最强。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 动词时态 =================
    {
        "node": "动词时态",
        "variant": "一般时态",
        "kind": "choice",
        "stem": "The train ______ at 9:30 every morning, so we needn't hurry.",
        "options": ["A. leaves", "B. left", "C. has left", "D. is leaving"],
        "answer": "A",
        "explain": "every morning表明是经常性动作，列车时刻用一般现在时；is leaving表近期安排不合every morning。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "动词时态",
        "variant": "一般时态",
        "kind": "fill",
        "stem": "When I was young, my grandmother often ______ (tell) me stories every night.",
        "options": [],
        "answer": "told",
        "explain": "When I was young及every night表明是过去的习惯，用一般过去时told。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "动词时态",
        "variant": "进行时态",
        "kind": "choice",
        "stem": "Don't take the dictionary away; I ______ it now.",
        "options": ["A. use", "B. used", "C. am using", "D. have used"],
        "answer": "C",
        "explain": "now标志此刻正在进行，用现在进行时am using；use为一般现在时不合语境。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "动词时态",
        "variant": "进行时态",
        "kind": "fill",
        "stem": "Listen! Someone ______ (sing) in the next room.",
        "options": [],
        "answer": "is singing",
        "explain": "Listen!提示动作此刻正在进行，用现在进行时is singing。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "动词时态",
        "variant": "完成时态",
        "kind": "choice",
        "stem": "Great changes ______ in my hometown in the past ten years.",
        "options": ["A. took place", "B. have taken place", "C. were taken place", "D. are taking place"],
        "answer": "B",
        "explain": "in the past ten years与现在完成时连用；take place不及物，不能用于被动，故C错。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "动词时态",
        "variant": "完成时态",
        "kind": "fill",
        "stem": "She ______ (finish) her homework already, so she can watch TV now.",
        "options": [],
        "answer": "has finished",
        "explain": "already与现在完成时连用，表示动作已完成并对现在造成影响。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "动词时态",
        "variant": "时态呼应",
        "kind": "choice",
        "stem": "He told me that he ______ the film the day before.",
        "options": ["A. saw", "B. has seen", "C. had seen", "D. would see"],
        "answer": "C",
        "explain": "主句told为过去时，the day before指过去某时之前，宾语从句用过去完成时。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "动词时态",
        "variant": "时态呼应",
        "kind": "fill",
        "stem": "She said she ______ (visit) the museum the next day.",
        "options": [],
        "answer": "would visit",
        "explain": "主句said为过去时，the next day指过去的将来，宾语从句用过去将来时would visit。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 主谓一致 =================
    {
        "node": "主谓一致",
        "variant": "就近原则",
        "kind": "choice",
        "stem": "Not only the students but also their teacher ______ invited to the party.",
        "options": ["A. was", "B. were", "C. are", "D. have been"],
        "answer": "A",
        "explain": "not only...but also...谓语就近一致，与their teacher（单数）一致用was。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主谓一致",
        "variant": "就近原则",
        "kind": "fill",
        "stem": "Either Tom or his parents ______ (be) going to attend the meeting tomorrow.",
        "options": [],
        "answer": "are",
        "explain": "either...or...谓语就近一致，与最近的his parents（复数）一致，用are。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主谓一致",
        "variant": "意义一致",
        "kind": "choice",
        "stem": "The police ______ searching for the lost child in the forest.",
        "options": ["A. is", "B. are", "C. was", "D. has been"],
        "answer": "B",
        "explain": "police是集合名词，谓语总是用复数，且语境是正在进行的动作。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主谓一致",
        "variant": "意义一致",
        "kind": "fill",
        "stem": "Every means ______ (have) been tried to solve the problem.",
        "options": [],
        "answer": "has",
        "explain": "means单复数同形，被every修饰视为单数，助动词用has。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主谓一致",
        "variant": "主语后置修饰",
        "kind": "choice",
        "stem": "The number of students in our school ______ increasing year by year.",
        "options": ["A. is", "B. are", "C. were", "D. have been"],
        "answer": "A",
        "explain": "The number of...（……的数量）作主语时谓语用单数；A number of才用复数。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主谓一致",
        "variant": "主语后置修饰",
        "kind": "fill",
        "stem": "Mr. Wang, together with his students, ______ (go) to plant trees every spring.",
        "options": [],
        "answer": "goes",
        "explain": "together with引导的成分只是伴随状语，谓语与Mr. Wang（单数）一致，用goes。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主谓一致",
        "variant": "集体名词",
        "kind": "choice",
        "stem": "My family ______ a big one, and all of us get on well.",
        "options": ["A. is", "B. are", "C. were", "D. have"],
        "answer": "A",
        "explain": "family指整体（一个大家庭）时谓语用单数；指成员时才用复数。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "主谓一致",
        "variant": "集体名词",
        "kind": "fill",
        "stem": "The population of China ______ (be) larger than that of any other country in Asia.",
        "options": [],
        "answer": "is",
        "explain": "population作主语指人口整体数量时谓语用单数is。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 情态动词 =================
    {
        "node": "情态动词",
        "variant": "推测（肯定）",
        "kind": "choice",
        "stem": "The light is still on in the office; our teacher ______ still be working.",
        "options": ["A. must", "B. can", "C. would", "D. should"],
        "answer": "A",
        "explain": "灯还亮着推出'肯定还在工作'，must表肯定推测；can不用于肯定句推测。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词",
        "variant": "推测（肯定）",
        "kind": "fill",
        "stem": "You have worked for ten hours, so you ______ (be) very tired now.",
        "options": [],
        "answer": "must",
        "explain": "依据'工作十小时'作出肯定推测'一定很累'，用must be。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词",
        "variant": "推测（否定）",
        "kind": "choice",
        "stem": "The light in his room is off. He ______ be sleeping now.",
        "options": ["A. can't", "B. mustn't", "C. needn't", "D. shouldn't"],
        "answer": "A",
        "explain": "灯灭了推出'不可能在睡觉'，否定推测用can't；mustn't表禁止不作推测。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词",
        "variant": "推测（否定）",
        "kind": "fill",
        "stem": "Tom was playing basketball just now, so he ______ (can) be in the library.",
        "options": [],
        "answer": "can't",
        "explain": "刚在打球推出'不可能在图书馆'，否定推测用can't。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词",
        "variant": "必要与许可",
        "kind": "choice",
        "stem": "You ______ return the book within two weeks, or you'll be fined.",
        "options": ["A. must", "B. can", "C. may", "D. would"],
        "answer": "A",
        "explain": "否则会被罚款说明是必须履行的义务，用must；can/may表许可不合语境。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词",
        "variant": "必要与许可",
        "kind": "fill",
        "stem": "—Must I hand in my homework today? —No, you ______ (need). You can hand it in tomorrow.",
        "options": [],
        "answer": "needn't",
        "explain": "Must开头的一般疑问句否定回答用needn't，表示'不必'。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词",
        "variant": "情态动词+完成式",
        "kind": "choice",
        "stem": "He ______ have attended the meeting yesterday, for he was on a business trip in Shanghai.",
        "options": ["A. can't", "B. mustn't", "C. needn't", "D. shouldn't"],
        "answer": "A",
        "explain": "在外出差推出'不可能参加了会议'，can't have done表对过去的否定推测。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "情态动词",
        "variant": "情态动词+完成式",
        "kind": "fill",
        "stem": "The ground is wet; it ______ (rain) last night.",
        "options": [],
        "answer": "must have rained",
        "explain": "依据地面湿了推测过去肯定下过雨，用must have done表对过去的肯定推测。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 虚拟语气 =================
    {
        "node": "虚拟语气",
        "variant": "与现在相反",
        "kind": "choice",
        "stem": "If I ______ you, I would take the job.",
        "options": ["A. am", "B. was", "C. were", "D. be"],
        "answer": "C",
        "explain": "与现在事实相反，if从句用过去式，be一律用were。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "虚拟语气",
        "variant": "与现在相反",
        "kind": "fill",
        "stem": "If there ______ (be) no air, nothing could live on the earth.",
        "options": [],
        "answer": "were",
        "explain": "与现在事实相反的非真实条件句，be动词用were。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "虚拟语气",
        "variant": "与过去相反",
        "kind": "choice",
        "stem": "If he ______ my advice, he wouldn't have failed the exam.",
        "options": ["A. took", "B. had taken", "C. would take", "D. has taken"],
        "answer": "B",
        "explain": "与过去事实相反，if从句用过去完成时had taken。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "虚拟语气",
        "variant": "与过去相反",
        "kind": "fill",
        "stem": "She wishes that she ______ (study) harder when she was young.",
        "options": [],
        "answer": "had studied",
        "explain": "wish后宾语从句表与过去事实相反的愿望，用过去完成时had studied。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "虚拟语气",
        "variant": "与将来相反",
        "kind": "choice",
        "stem": "If it ______ rain tomorrow, we would hold the sports meeting.",
        "options": ["A. shouldn't", "B. doesn't", "C. won't", "D. wouldn't"],
        "answer": "A",
        "explain": "与将来事实相反可用should+动词原形；主句would+原形呼应。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "虚拟语气",
        "variant": "与将来相反",
        "kind": "fill",
        "stem": "We would put off the match ______ it rain tomorrow.",
        "options": [],
        "answer": "should",
        "explain": "与将来相反的虚拟条件句可用should+动词原形，此处省略if用should引导。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "虚拟语气",
        "variant": "名词性从句中的虚拟",
        "kind": "choice",
        "stem": "The doctor suggested that he ______ more exercise every day.",
        "options": ["A. takes", "B. take", "C. took", "D. would take"],
        "answer": "B",
        "explain": "suggest表'建议'时宾语从句用(should)+动词原形，故用take。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "虚拟语气",
        "variant": "名词性从句中的虚拟",
        "kind": "fill",
        "stem": "It is important that every student ______ (know) the safety rules.",
        "options": [],
        "answer": "know",
        "explain": "It is important that...主语从句用虚拟语气，谓语用(should)+动词原形know。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 倒装句 =================
    {
        "node": "倒装句",
        "variant": "否定词提前的部分倒装",
        "kind": "choice",
        "stem": "Not until he came back ______ the truth.",
        "options": ["A. did I know", "B. I knew", "C. I did know", "D. knew I"],
        "answer": "A",
        "explain": "Not until位于句首，主句用部分倒装did I know；B未倒装，D为完全倒装错误。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倒装句",
        "variant": "否定词提前的部分倒装",
        "kind": "fill",
        "stem": "Never ______ I seen such a beautiful sunrise before.",
        "options": [],
        "answer": "have",
        "explain": "否定副词Never置于句首引起部分倒装，助动词have提到主语I之前。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倒装句",
        "variant": "only+状语的倒装",
        "kind": "choice",
        "stem": "Only when you lose something ______ its value.",
        "options": ["A. you realize", "B. do you realize", "C. you do realize", "D. realize you"],
        "answer": "B",
        "explain": "Only+状语从句置于句首，主句部分倒装do you realize；A未倒装。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倒装句",
        "variant": "only+状语的倒装",
        "kind": "fill",
        "stem": "Only in this way ______ we make progress in English.",
        "options": [],
        "answer": "can",
        "explain": "Only+介词短语置于句首，主句部分倒装，情态动词can提前。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倒装句",
        "variant": "完全倒装",
        "kind": "choice",
        "stem": "On the wall ______ two large paintings.",
        "options": ["A. hang", "B. hangs", "C. is", "D. was"],
        "answer": "A",
        "explain": "地点状语提前构成完全倒装，谓语动词提到主语前，主语two paintings为复数用hang。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倒装句",
        "variant": "完全倒装",
        "kind": "fill",
        "stem": "South of the city ______ (lie) two beautiful lakes.",
        "options": [],
        "answer": "lie",
        "explain": "地点状语South of the city提前，谓语lie完全倒装到主语two lakes之前，主语复数用lie。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倒装句",
        "variant": "so/neither句型",
        "kind": "choice",
        "stem": "—I have never been to Tibet. —______.",
        "options": ["A. So have I", "B. Neither have I", "C. Neither do I", "D. So do I"],
        "answer": "B",
        "explain": "前句为否定句，'我也不'用Neither have I，助动词与前句have保持一致。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "倒装句",
        "variant": "so/neither句型",
        "kind": "fill",
        "stem": "—I have finished my report. —So ______ my deskmate.",
        "options": [],
        "answer": "have",
        "explain": "So+助动词+主语表示'某人也是'，前句用have finished，倒装句用So have my deskmate。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 强调句 =================
    {
        "node": "强调句",
        "variant": "基本型",
        "kind": "choice",
        "stem": "It was in the park ______ I first met my best friend.",
        "options": ["A. that", "B. where", "C. which", "D. when"],
        "answer": "A",
        "explain": "强调句型It is/was+被强调部分+that...；去掉It was...that句子仍完整。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "强调句",
        "variant": "基本型",
        "kind": "fill",
        "stem": "It ______ not until midnight that he came back.",
        "options": [],
        "answer": "was",
        "explain": "came back表明是过去的事，强调句用It was not until...that...。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "强调句",
        "variant": "强调人",
        "kind": "choice",
        "stem": "It was my English teacher ______ helped me regain my confidence.",
        "options": ["A. who", "B. whom", "C. which", "D. whose"],
        "answer": "A",
        "explain": "强调人且被强调部分在从句中作主语，用who（或that）；whom只作宾语。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "强调句",
        "variant": "强调人",
        "kind": "choice",
        "stem": "—Who was it that called me this morning? —______ was your uncle.",
        "options": ["A. It", "B. He", "C. That", "D. This"],
        "answer": "A",
        "explain": "强调句的特殊疑问句及回答都用It，指被强调的对象。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "强调句",
        "variant": "句型辨析",
        "kind": "choice",
        "stem": "It was 10 o'clock ______ he arrived at the station.",
        "options": ["A. that", "B. when", "C. since", "D. until"],
        "answer": "B",
        "explain": "10 o'clock前无介词at，不是强调句而是时间状语从句，用when；强调句应为It was at 10 o'clock that...。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "强调句",
        "variant": "句型辨析",
        "kind": "choice",
        "stem": "Was it during the Second World War ______ he died?",
        "options": ["A. when", "B. that", "C. which", "D. in which"],
        "answer": "B",
        "explain": "强调句一般疑问句式Was it+被强调部分+that...；during已含介词，无需in which。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "强调句",
        "variant": "not...until的强调",
        "kind": "choice",
        "stem": "It was not until she took off her glasses ______ I recognized her.",
        "options": ["A. that", "B. when", "C. then", "D. so"],
        "answer": "A",
        "explain": "not...until的强调句式为It was not until...that...，从句不再倒装。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "强调句",
        "variant": "not...until的强调",
        "kind": "fill",
        "stem": "It was because of the heavy snow ______ the flight was delayed.",
        "options": [],
        "answer": "that",
        "explain": "强调原因状语because of the heavy snow，用强调句型It was...that...。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 被动语态 =================
    {
        "node": "被动语态",
        "variant": "一般时态的被动",
        "kind": "choice",
        "stem": "The new bridge ______ in 2020, and it has been in use ever since.",
        "options": ["A. built", "B. was built", "C. is built", "D. has built"],
        "answer": "B",
        "explain": "bridge与build是被动关系，in 2020表过去时间，用一般过去时被动was built。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "被动语态",
        "variant": "一般时态的被动",
        "kind": "fill",
        "stem": "English ______ (speak) in many countries around the world.",
        "options": [],
        "answer": "is spoken",
        "explain": "English与speak是被动关系，表客观事实用一般现在时被动is spoken。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "被动语态",
        "variant": "进行/完成时的被动",
        "kind": "choice",
        "stem": "A new cinema ______ in our town now; it will be open next year.",
        "options": ["A. is built", "B. is being built", "C. has been built", "D. was built"],
        "answer": "B",
        "explain": "now表明正在建，用现在进行时被动is being built；C已完成与next year矛盾。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "被动语态",
        "variant": "进行/完成时的被动",
        "kind": "fill",
        "stem": "So far, the old temple ______ (repair) twice.",
        "options": [],
        "answer": "has been repaired",
        "explain": "So far与现在完成时连用，temple与repair是被动关系，用has been repaired。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "被动语态",
        "variant": "含情态动词的被动",
        "kind": "choice",
        "stem": "The problem must ______ at once, or it will get worse.",
        "options": ["A. deal with", "B. be dealt with", "C. be dealt", "D. have dealt"],
        "answer": "B",
        "explain": "情态动词后被动式为be done，deal with中的介词with不能省略。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "被动语态",
        "variant": "含情态动词的被动",
        "kind": "fill",
        "stem": "These flowers should ______ (water) every day.",
        "options": [],
        "answer": "be watered",
        "explain": "情态动词should后接be+过去分词构成被动语态be watered。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "被动语态",
        "variant": "不定式被动与主动表被动",
        "kind": "choice",
        "stem": "The book is said ______ into twenty languages.",
        "options": ["A. to have translated", "B. to have been translated", "C. to translate", "D. being translated"],
        "answer": "B",
        "explain": "book与translate是被动关系且动作已完成，用不定式完成被动式to have been translated。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "被动语态",
        "variant": "不定式被动与主动表被动",
        "kind": "choice",
        "stem": "This kind of pen ______ smoothly and is popular with students.",
        "options": ["A. is written", "B. writes", "C. is writing", "D. wrote"],
        "answer": "B",
        "explain": "write表示笔'写起来'的性能时用主动形式表被动意义，且为一般现在时。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= it的用法 =================
    {
        "node": "it的用法",
        "variant": "it指代",
        "kind": "choice",
        "stem": "—Who is knocking at the door? —______ must be the postman.",
        "options": ["A. It", "B. He", "C. That", "D. This"],
        "answer": "A",
        "explain": "指代身份不明的人（敲门者）用it；He指已知身份的具体的人。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "it的用法",
        "variant": "it指代",
        "kind": "fill",
        "stem": "The task itself is not difficult, but ______ takes time.",
        "options": [],
        "answer": "it",
        "explain": "it指代前面提到的the task，作后句主语。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "it的用法",
        "variant": "形式主语",
        "kind": "choice",
        "stem": "______ is a pity that you missed the wonderful concert.",
        "options": ["A. It", "B. That", "C. This", "D. What"],
        "answer": "A",
        "explain": "It作形式主语，真正主语是that从句；其余词不能作形式主语。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "it的用法",
        "variant": "形式主语",
        "kind": "fill",
        "stem": "It took me two hours ______ (finish) the report.",
        "options": [],
        "answer": "to finish",
        "explain": "It takes sb. some time to do sth.中it作形式主语，真正主语是不定式to finish。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "it的用法",
        "variant": "形式宾语",
        "kind": "choice",
        "stem": "The Internet makes ______ possible for us to get the latest news in seconds.",
        "options": ["A. it", "B. that", "C. this", "D. us"],
        "answer": "A",
        "explain": "it作形式宾语，真正的宾语是后面的不定式；that/this无此用法。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "it的用法",
        "variant": "形式宾语",
        "kind": "fill",
        "stem": "I find ______ hard to get along with strangers at first.",
        "options": [],
        "answer": "it",
        "explain": "find+it+形容词+to do结构中，it作形式宾语，代替真正宾语to get along with...",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "it的用法",
        "variant": "固定句型",
        "kind": "choice",
        "stem": "______ is no use arguing with him; he never changes his mind.",
        "options": ["A. It", "B. There", "C. That", "D. This"],
        "answer": "A",
        "explain": "It is no use doing sth.为固定句型，it作形式主语；There无此句型。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "it的用法",
        "variant": "固定句型",
        "kind": "fill",
        "stem": "It is two years ______ we last met in Beijing.",
        "options": [],
        "answer": "since",
        "explain": "It is/has been+时间段+since...表示'自从……以来已有……'，为固定句型。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 独立主格结构 =================
    {
        "node": "独立主格结构",
        "variant": "名词+现在分词",
        "kind": "choice",
        "stem": "Weather ______, we'll go outing tomorrow.",
        "options": ["A. permitting", "B. permitted", "C. permits", "D. to permit"],
        "answer": "A",
        "explain": "Weather permitting为独立主格，weather与permit是主动关系用现在分词；C为谓语错误。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "独立主格结构",
        "variant": "名词+现在分词",
        "kind": "fill",
        "stem": "Night ______ (fall), we hurried home.",
        "options": [],
        "answer": "falling",
        "explain": "night与fall是主动关系，独立主格用现在分词falling表示伴随的原因。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "独立主格结构",
        "variant": "名词+过去分词",
        "kind": "choice",
        "stem": "Everything ______ into consideration, his plan seems more practical.",
        "options": ["A. taken", "B. taking", "C. to take", "D. is taken"],
        "answer": "A",
        "explain": "everything与take是被动关系，独立主格用过去分词taken；D是谓语形式，两句间无连词。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "独立主格结构",
        "variant": "名词+过去分词",
        "kind": "fill",
        "stem": "His homework ______ (finish), the boy went out to play.",
        "options": [],
        "answer": "finished",
        "explain": "homework与finish是被动关系且已完成，独立主格用过去分词finished。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "独立主格结构",
        "variant": "名词+形容词/介词短语",
        "kind": "choice",
        "stem": "He stood at the gate, his hands ______ in his pockets.",
        "options": ["A. deep", "B. deeply", "C. depth", "D. deepen"],
        "answer": "A",
        "explain": "独立主格'名词+形容词'结构；deep in表'深深插入'用形容词deep，deeply表抽象程度。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "独立主格结构",
        "variant": "名词+形容词/介词短语",
        "kind": "fill",
        "stem": "The singer came onto the stage, microphone ______ hand.",
        "options": [],
        "answer": "in",
        "explain": "独立主格'名词+介词短语'结构：microphone in hand表示'手持话筒'。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "独立主格结构",
        "variant": "with复合结构",
        "kind": "choice",
        "stem": "With the problem ______, we all felt relaxed.",
        "options": ["A. settled", "B. settling", "C. to settle", "D. settle"],
        "answer": "A",
        "explain": "problem与settle是被动关系且已完成，with复合结构用过去分词settled；C表将来不合语义。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "独立主格结构",
        "variant": "with复合结构",
        "kind": "fill",
        "stem": "With the light ______ (burn), he fell asleep.",
        "options": [],
        "answer": "burning",
        "explain": "light与burn是主动关系且灯一直亮着，with复合结构用现在分词burning。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= there be 句型 =================
    {
        "node": "there be 句型",
        "variant": "主谓一致与就近",
        "kind": "choice",
        "stem": "There ______ a pen, two books and some paper on the desk.",
        "options": ["A. is", "B. are", "C. has", "D. have"],
        "answer": "A",
        "explain": "there be句型谓语就近一致，与最近的a pen（单数）一致用is；have与be不能混用。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "there be 句型",
        "variant": "主谓一致与就近",
        "kind": "fill",
        "stem": "There ______ (be) plenty of time left, so don't hurry.",
        "options": [],
        "answer": "is",
        "explain": "plenty of time为不可数意义，there be谓语用单数is。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "there be 句型",
        "variant": "时态变化",
        "kind": "choice",
        "stem": "There ______ a meeting tomorrow afternoon.",
        "options": ["A. will be", "B. is going to have", "C. will have", "D. has"],
        "answer": "A",
        "explain": "there be表'有'，将来时用there will be；there be句型不能说there will have。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "there be 句型",
        "variant": "时态变化",
        "kind": "fill",
        "stem": "There ______ (be) great changes in my hometown in the past five years.",
        "options": [],
        "answer": "have been",
        "explain": "in the past five years与现在完成时连用，changes为复数，用there have been。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "there be 句型",
        "variant": "there be的非谓语形式",
        "kind": "choice",
        "stem": "There ______ no bus, we had to walk home.",
        "options": ["A. being", "B. was", "C. is", "D. be"],
        "answer": "A",
        "explain": "两句间无连词，前半部分用there being构成独立主格结构表原因。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "there be 句型",
        "variant": "there be的非谓语形式",
        "kind": "fill",
        "stem": "I don't want there ______ (be) any misunderstanding between us.",
        "options": [],
        "answer": "to be",
        "explain": "want后接不定式作宾语补足语，there be结构的不定式为there to be。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "there be 句型",
        "variant": "固定句式",
        "kind": "choice",
        "stem": "______ used to be a temple at the foot of the mountain.",
        "options": ["A. There", "B. It", "C. That", "D. This"],
        "answer": "A",
        "explain": "'过去有'用there used to be；It无此存在句用法。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "there be 句型",
        "variant": "固定句式",
        "kind": "fill",
        "stem": "There is no ______ (tell) what will happen in the future.",
        "options": [],
        "answer": "telling",
        "explain": "There is no doing...为固定句型，表示'无法……'，用动名词telling。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 比较结构 =================
    {
        "node": "比较结构",
        "variant": "原级比较",
        "kind": "choice",
        "stem": "He is not so ______ at maths as his brother.",
        "options": ["A. good", "B. well", "C. better", "D. best"],
        "answer": "A",
        "explain": "not so...as为原级比较，用形容词原级；be good at为固定搭配。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "比较结构",
        "variant": "原级比较",
        "kind": "fill",
        "stem": "My hometown is twice as ______ (big) as it was ten years ago.",
        "options": [],
        "answer": "big",
        "explain": "倍数+as+原级+as为固定结构，as...as之间用形容词原级big。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "比较结构",
        "variant": "比较级",
        "kind": "choice",
        "stem": "The harder you work, ______ progress you will make.",
        "options": ["A. the greater", "B. greater", "C. the greatest", "D. great"],
        "answer": "A",
        "explain": "'the+比较级..., the+比较级...'表示'越……越……'，后句用the greater。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "比较结构",
        "variant": "比较级",
        "kind": "fill",
        "stem": "Nothing is ______ (important) than health.",
        "options": [],
        "answer": "more important",
        "explain": "有than提示用比较级，important是多音节词，比较级为more important。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "比较结构",
        "variant": "倍数表达",
        "kind": "choice",
        "stem": "The dining hall in our school is three times ______ the old one.",
        "options": ["A. as larger as", "B. larger as", "C. as large as", "D. the largest"],
        "answer": "C",
        "explain": "倍数+as+原级+as为正确倍数表达；A中as larger as结构错误。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "比较结构",
        "variant": "倍数表达",
        "kind": "fill",
        "stem": "The river is twice the ______ (long) of that one.",
        "options": [],
        "answer": "length",
        "explain": "倍数+the+名词+of...为倍数表达法之一，long的名词形式是length。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "比较结构",
        "variant": "固定比较句式",
        "kind": "choice",
        "stem": "—How is your father now? —He is getting ______.",
        "options": ["A. better and better", "B. well and well", "C. more better", "D. good and good"],
        "answer": "A",
        "explain": "'比较级+and+比较级'表示'越来越……'，well的比较级是better；more better重复比较级。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "比较结构",
        "variant": "固定比较句式",
        "kind": "fill",
        "stem": "Mary is the ______ (tall) of the two sisters.",
        "options": [],
        "answer": "taller",
        "explain": "'the+比较级+of the two'表示'两者中较……的'，用taller而非tallest。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },

    # ================= 直接引语与间接引语 =================
    {
        "node": "直接引语与间接引语",
        "variant": "陈述句转换",
        "kind": "choice",
        "stem": "He said, \"I saw the film last week.\" → He said that he ______ the film the week before.",
        "options": ["A. saw", "B. had seen", "C. has seen", "D. would see"],
        "answer": "B",
        "explain": "主句said为过去时，直接引语的过去式saw变为过去完成时had seen。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "直接引语与间接引语",
        "variant": "陈述句转换",
        "kind": "fill",
        "stem": "She said to me, \"I have lost my keys.\" → She told me that she ______ (lose) her keys.",
        "options": [],
        "answer": "had lost",
        "explain": "主句为过去时，直接引语的现在完成时have lost变间接引语时改为过去完成时had lost。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "直接引语与间接引语",
        "variant": "一般疑问句转换",
        "kind": "choice",
        "stem": "He asked me, \"Do you like playing football?\" → He asked me ______ I liked playing football.",
        "options": ["A. that", "B. if", "C. what", "D. which"],
        "answer": "B",
        "explain": "一般疑问句变间接引语用if/whether引导，语序改为陈述语序；that不能引导是非问句。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "直接引语与间接引语",
        "variant": "一般疑问句转换",
        "kind": "fill",
        "stem": "The teacher asked, \"Are you ready?\" → The teacher asked ______ or not we were ready.",
        "options": [],
        "answer": "whether",
        "explain": "与or not连用时只能用whether；if不与or not直接连用。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "直接引语与间接引语",
        "variant": "特殊疑问句转换",
        "kind": "choice",
        "stem": "He asked, \"Where do you live?\" → He asked me where ______.",
        "options": ["A. do I live", "B. I lived", "C. did I live", "D. I live"],
        "answer": "B",
        "explain": "特殊疑问句变间接引语用陈述语序且时态后移，故为I lived。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "直接引语与间接引语",
        "variant": "特殊疑问句转换",
        "kind": "fill",
        "stem": "She asked me, \"What are you doing?\" → She asked me what I ______ (do).",
        "options": [],
        "answer": "was doing",
        "explain": "主句asked为过去时，直接引语的现在进行时变间接引语时改为过去进行时was doing。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "直接引语与间接引语",
        "variant": "祈使句转换",
        "kind": "choice",
        "stem": "\"Don't smoke here,\" the doctor said to him. → The doctor told him ______ smoke there.",
        "options": ["A. not to", "B. to not", "C. don't", "D. doesn't"],
        "answer": "A",
        "explain": "否定祈使句变间接引语用tell sb. not to do；不定式否定式not须放在to之前。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
    {
        "node": "直接引语与间接引语",
        "variant": "祈使句转换",
        "kind": "fill",
        "stem": "\"Please open the window,\" she said. → She asked me ______ (open) the window.",
        "options": [],
        "answer": "to open",
        "explain": "肯定祈使句变间接引语用ask/tell sb. to do结构，用不定式to open。",
        "source": "自编练习（2026-08-31，未人工复核）",
        "verified": False,
    },
]
