# -*- coding: utf-8 -*-
"""知识节点题池补充批次 E：语篇·阅读 6 节点 + 语法根节点「句子成分与基本句型」。

背景（2026-09-22）：知识体系原有 50 节点里「语篇」为 0 —— 而阅读题的 74% 是
细节题与推理题。本批为新增的 7 个节点各出 8 道题（共 56 道），使题池校验
（每节点 ≥8 道）通过。schema 与 a/b/c/d 完全一致。

节点：细节理解题 / 推理判断题 / 词句猜测题 / 主旨大意题 / 标题归纳题 /
     观点态度与写作意图 / 句子成分与基本句型

全部为自编练习，verified=False（未人工复核），source 如实标注、不假托真题出处。
"""
QUESTIONS = [
    # ---------- 句子成分与基本句型（变体：主谓与主谓宾 / 主系表与表语 / 双宾与宾语补足语 / 定语与状语） ----------
    {"node": "句子成分与基本句型", "variant": "主谓与主谓宾", "kind": "choice",
     "stem": "The children are playing happily in the park. 该句属于哪种基本句型？",
     "options": ["A. 主谓", "B. 主谓宾", "C. 主系表", "D. 主谓双宾"], "answer": "A",
     "explain": "are playing 是不及物动词短语，后面没有宾语；happily 和 in the park 都是状语，所以是主谓结构。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "句子成分与基本句型", "variant": "主谓与主谓宾", "kind": "fill",
     "stem": "He ______ me a book yesterday.（give 的正确形式）",
     "options": [], "answer": "gave",
     "explain": "主谓双宾结构 give sb sth；yesterday 表过去，用过去式 gave。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "句子成分与基本句型", "variant": "主系表与表语", "kind": "choice",
     "stem": "She became a doctor last year. 句中作表语的是哪一部分？",
     "options": ["A. She", "B. became", "C. a doctor", "D. last year"], "answer": "C",
     "explain": "became 是系动词，后面的 a doctor 说明主语的身份，是表语；last year 是时间状语。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "句子成分与基本句型", "variant": "主系表与表语", "kind": "choice",
     "stem": "The music sounds ______.",
     "options": ["A. beautiful", "B. beautifully", "C. beauty", "D. beautify"], "answer": "A",
     "explain": "sounds 是系动词，后面接形容词作表语；beautifully 是副词，只能修饰动词。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "句子成分与基本句型", "variant": "双宾与宾语补足语", "kind": "choice",
     "stem": "We elected him ______.",
     "options": ["A. our monitor", "B. is our monitor", "C. being our monitor", "D. to our monitor"], "answer": "A",
     "explain": "elect 是主谓宾补结构：him 是宾语，our monitor 补充说明宾语的身份，作宾语补足语，用名词短语即可。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "句子成分与基本句型", "variant": "双宾与宾语补足语", "kind": "fill",
     "stem": "The teacher asked us to keep the classroom ______.（clean 的正确形式）",
     "options": [], "answer": "clean",
     "explain": "keep + 宾语 + 宾语补足语，补足语说明宾语的状态，用形容词 clean。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "句子成分与基本句型", "variant": "定语与状语", "kind": "choice",
     "stem": "The girl in red is my sister. 句中 in red 作什么成分？",
     "options": ["A. 定语", "B. 状语", "C. 表语", "D. 宾语"], "answer": "A",
     "explain": "in red 限定 the girl「哪一个」，修饰名词，所以是定语。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "句子成分与基本句型", "variant": "定语与状语", "kind": "choice",
     "stem": "The boy ______ there is my brother.",
     "options": ["A. stand", "B. standing", "C. stood", "D. to stand"], "answer": "B",
     "explain": "句子已有谓语 is，空处只能是非谓语；boy 与 stand 是主动关系，作后置定语用现在分词 standing。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},

    # ---------- 细节理解题（变体：定位词选择 / 定位句读全 / 排除法 / 同义改写） ----------
    {"node": "细节理解题", "variant": "定位词选择", "kind": "choice",
     "stem": "题干：How much did the ticket cost in 2024? 回原文定位时最省事的定位词是哪一个？",
     "options": ["A. ticket", "B. cost", "C. 2024", "D. How much"], "answer": "C",
     "explain": "数字在原文出现次数最少、最独特，定位最快；ticket 与 cost 都是高频普通词，定位效率低。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "细节理解题", "variant": "定位词选择", "kind": "choice",
     "stem": "题干问 Cardiff 的博物馆何时开门。原文含 Cardiff / museum / opens / 9 a.m. 四个词，优先用哪个定位？",
     "options": ["A. Cardiff", "B. museum", "C. opens", "D. 四个都同等有效"], "answer": "A",
     "explain": "专有名词最独特、复现最少，先用 Cardiff 缩小范围比用 museum 这类通用词快得多。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "细节理解题", "variant": "定位句读全", "kind": "choice",
     "stem": "原文：The museum opens at 9 a.m. on weekdays but stays open until 8 p.m. at weekends. 周末开放到几点？",
     "options": ["A. 9 a.m.", "B. 8 p.m.", "C. 周末闭馆", "D. 原文没有说明"], "answer": "B",
     "explain": "but 之后给出周末信息 stays open until 8 p.m.；只读前半句就会误选 C。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "细节理解题", "variant": "定位句读全", "kind": "choice",
     "stem": "原文：Only visitors who book online in advance can join the guided tour. 哪些人可以参加导览？",
     "options": ["A. 所有游客", "B. 提前在网上预约的游客", "C. 现场买票的游客", "D. 持学生证的游客"], "answer": "B",
     "explain": "Only + who 引导的定语从句限定了条件：必须提前网上预约，选 B。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "细节理解题", "variant": "排除法", "kind": "choice",
     "stem": "原文说「仅限提前预约者可参加」，选项写成「所有人都可参加」。这属于哪一类错误选项？",
     "options": ["A. 偷换对象", "B. 扩大范围", "C. 因果倒置", "D. 无中生有"], "answer": "B",
     "explain": "把受限的条件放宽到全体，是典型的扩大范围。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "细节理解题", "variant": "排除法", "kind": "choice",
     "stem": "原文说 A 导致了 B，选项写成 B 导致了 A。这属于哪一类错误选项？",
     "options": ["A. 偷换对象", "B. 扩大范围", "C. 因果倒置", "D. 无中生有"], "answer": "C",
     "explain": "把因果两端对调，是因果倒置；这类选项通常照抄原文词汇，最容易误选。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "细节理解题", "variant": "同义改写", "kind": "choice",
     "stem": "原文：sales of high-sugar drinks fell by nearly a third. 与之意最接近的选项是？",
     "options": ["A. sales dropped by about 30%", "B. sales rose by about 30%",
                 "C. sales stayed almost the same", "D. sales doubled in a year"], "answer": "A",
     "explain": "nearly a third 约等于 30%，fell 与 dropped 同义；B 方向相反，C、D 与原文无关。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "细节理解题", "variant": "同义改写", "kind": "choice",
     "stem": "细节理解题的正确选项通常具有什么特征？",
     "options": ["A. 与原文用词完全相同", "B. 是原文某处的同义改写",
                 "C. 必须结合生活常识推断", "D. 概括全文大意"], "answer": "B",
     "explain": "正确项是原文的同义改写；与原文用词完全相同但逻辑颠倒的往往正是陷阱，选项 C、D 分别属推理题与主旨题。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},

    # ---------- 推理判断题（变体：推断方向 / 让步与转折 / 依据直接性 / 态度三档） ----------
    {"node": "推理判断题", "variant": "推断方向", "kind": "choice",
     "stem": "题干问 What is the author's purpose in writing the text? 回原文时应重点找什么？",
     "options": ["A. 表目的的不定式或 so that 从句", "B. 全文的高频实词",
                 "C. 文章标题的字数", "D. 最后一段里的数字"], "answer": "A",
     "explain": "问目的就找表目的的语法标记；高频词属主旨题的依据，数字属细节题的依据。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "推理判断题", "variant": "推断方向", "kind": "choice",
     "stem": "题干问 Where is the text most probably taken from? 判断依据主要是？",
     "options": ["A. 文本的语言风格与内容类型", "B. 作者的姓名",
                 "C. 文中出现的数字个数", "D. 引号内直接引语的数量"], "answer": "A",
     "explain": "出处题看的是文体特征：步骤加提醒多为操作指南，数据加结论多为研究报告。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "推理判断题", "variant": "让步与转折", "kind": "choice",
     "stem": "原文：Though the plan sounded perfect, few villagers signed up in the first month. 作者对该计划的态度最可能是？",
     "options": ["A. 完全支持", "B. 认为实际推行效果不佳", "C. 强烈反对并呼吁取消", "D. 完全不了解"], "answer": "B",
     "explain": "Though 让出的只是表象，few villagers signed up 才是落脚点，说明作者认为推行不顺，但并未到「强烈反对」。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "推理判断题", "variant": "让步与转折", "kind": "choice",
     "stem": "文中出现 Though / Although 引导的让步从句时，作者的落脚点通常在？",
     "options": ["A. 让步从句本身", "B. 主句", "C. 上一句", "D. 文章的标题"], "answer": "B",
     "explain": "让步从句的作用是先退一步，真正表达作者立场的是主句。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "推理判断题", "variant": "依据直接性", "kind": "choice",
     "stem": "原文只写了「他不停看表，并在下课铃前十分钟开始收拾笔记」。可以推出的是？",
     "options": ["A. 他当时很着急", "B. 他的朋友没有来",
                 "C. 他不喜欢这门课", "D. 他在等人"], "answer": "A",
     "explain": "看表与提前收拾两个动作直接支持「着急」；B、C、D 都是原文没有依据的补写。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "推理判断题", "variant": "依据直接性", "kind": "choice",
     "stem": "下列哪一种推断在高考推理题中是可以接受的？",
     "options": ["A. 有原文依据的合理延伸", "B. 符合生活常识但原文没有写",
                 "C. 与原文表述相反但更合情理", "D. 只凭个人经验的判断"], "answer": "A",
     "explain": "推理必须以原文为据；常识、个人经验、情理性都不能替代依据句。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "推理判断题", "variant": "态度三档", "kind": "choice",
     "stem": "某篇文本全篇解释现象、引用官方数据、不作任何评价。作者的态度应定为？",
     "options": ["A. positive", "B. negative", "C. objective", "D. doubtful"], "answer": "C",
     "explain": "只陈述事实与数据、不置评论，属客观（objective）态度。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "推理判断题", "variant": "态度三档", "kind": "choice",
     "stem": "高考态度题通常只考查哪三档？",
     "options": ["A. 支持 / 反对 / 客观", "B. 高兴 / 生气 / 难过",
                 "C. 强 / 中 / 弱", "D. 褒奖 / 贬低 / 讽刺"], "answer": "A",
     "explain": "态度题的标准答案只在支持、反对、客观三档内；情绪词与强度词都不是考查口径。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},

    # ---------- 词句猜测题（变体：同义线索 / 反义线索 / 举例与因果 / 代回验证） ----------
    {"node": "词句猜测题", "variant": "同义线索", "kind": "choice",
     "stem": "He is a nocturnal animal - he sleeps by day and hunts at night. 画线词 nocturnal 的意思是？",
     "options": ["A. 夜行的", "B. 昼行的", "C. 凶猛的", "D. 稀有的"], "answer": "A",
     "explain": "破折号后给出解释：白天睡、夜里活动，所以是夜行的。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "词句猜测题", "variant": "同义线索", "kind": "choice",
     "stem": "在词句猜测题中，破折号最常见的作用是？",
     "options": ["A. 对前面的内容作解释", "B. 表示转折", "C. 表示列举", "D. 表示结果"], "answer": "A",
     "explain": "破折号后往往就是对该词的解释，等于把词义直接告诉读者。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "词句猜测题", "variant": "反义线索", "kind": "choice",
     "stem": "Unlike her talkative brother, Anna is rather reticent. 画线词 reticent 的意思是？",
     "options": ["A. 沉默寡言的", "B. 健谈的", "C. 粗鲁的", "D. 乐观的"], "answer": "A",
     "explain": "Unlike 提示对照，reticent 应与 talkative 相反，故选沉默寡言。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "词句猜测题", "variant": "反义线索", "kind": "choice",
     "stem": "Unlike / but / however 这类词为猜测题提供的是哪一类线索？",
     "options": ["A. 同义线索", "B. 反义线索", "C. 举例线索", "D. 因果线索"], "answer": "B",
     "explain": "这三者都提示前后语义相反，顺着反义方向去取画线词的意思即可。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "词句猜测题", "variant": "举例与因果", "kind": "choice",
     "stem": "citrus fruits, such as oranges and lemons 中 such as 提供的是？",
     "options": ["A. 举例线索", "B. 反义线索", "C. 因果线索", "D. 顺序线索"], "answer": "A",
     "explain": "such as 后的词与画线词属于同一类，可据此确定词义的范围与类别。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "词句猜测题", "variant": "举例与因果", "kind": "choice",
     "stem": "The room was so cramped that we could hardly turn around in it. 画线词 cramped 的意思是？",
     "options": ["A. 狭小拥挤的", "B. 明亮的", "C. 安静的", "D. 干净的"], "answer": "A",
     "explain": "so...that 引出结果「几乎转不开身」，据此反推 cramped 指狭小拥挤。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "词句猜测题", "variant": "代回验证", "kind": "choice",
     "stem": "用上下文猜出词义之后，最后一步应该做什么？",
     "options": ["A. 把选项代回原句读一遍", "B. 直接选定不再检查",
                 "C. 立刻查词典确认拼写", "D. 跳过该题"], "answer": "A",
     "explain": "代回原句是唯一能验证答案的动作；替换后语义或搭配别扭的直接排除。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "词句猜测题", "variant": "代回验证", "kind": "choice",
     "stem": "词句猜测题考查的核心能力是什么？",
     "options": ["A. 是否认识画线单词", "B. 能否用上下文推断词义",
                 "C. 语法分析能力", "D. 单词拼写准确度"], "answer": "B",
     "explain": "命题意图正是「不认识也能做对」，靠的是上下文线索与代回验证。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},

    # ---------- 主旨大意题（变体：首尾段定话题 / 段首句串框架 / 高频复现词 / 过宽过窄排除） ----------
    {"node": "主旨大意题", "variant": "首尾段定话题", "kind": "choice",
     "stem": "主旨大意题问的到底是什么？",
     "options": ["A. 作者为什么写这篇文章", "B. 文中某一个细节",
                 "C. 某个生僻词的意思", "D. 作者的具体态度"], "answer": "A",
     "explain": "主旨题问的是全文的话题与写作意图；细节、猜词、态度分别属于另外三类题。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "主旨大意题", "variant": "首尾段定话题", "kind": "choice",
     "stem": "某文首段提出问题、末段给出应对办法。合格的主旨表述应当？",
     "options": ["A. 只写问题", "B. 只写应对办法",
                 "C. 同时涵盖问题与应对", "D. 写作者的个人经历"], "answer": "C",
     "explain": "只要漏掉一半（问题或应对），就属于过窄；主旨必须覆盖全文的话题范围。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "主旨大意题", "variant": "段首句串框架", "kind": "choice",
     "stem": "把文章各段的首句串起来读，主要用来判断什么？",
     "options": ["A. 全文的推进框架", "B. 文章的生词量",
                 "C. 语法的难度", "D. 全文的字数"], "answer": "A",
     "explain": "段落首句通常承载该段主旨，串起来就是全文的框架与推进方向。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "主旨大意题", "variant": "段首句串框架", "kind": "choice",
     "stem": "某文三段首句分别是 What is a plant? / Why do plants help us? / Which plants are easy to grow? 全文主旨最可能是？",
     "options": ["A. 室内植物的定义、好处与选择", "B. 植物学的发展史",
                 "C. 如何做植物实验", "D. 花卉市场的经营"], "answer": "A",
     "explain": "三段首句合起来正好是定义、好处、选择三个角度，覆盖全文。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "主旨大意题", "variant": "高频复现词", "kind": "choice",
     "stem": "判断全文主题词最省事的办法是？",
     "options": ["A. 看全文高频复现的实词", "B. 看标题的字号大小",
                 "C. 看第一段的第一个词", "D. 看作者的姓名"], "answer": "A",
     "explain": "复现三次以上的实词几乎一定是主题词，是定位主旨最快的抓手。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "主旨大意题", "variant": "高频复现词", "kind": "choice",
     "stem": "某文反复出现 friendship / distance / keep in touch / video call 等词。全文主旨最可能是？",
     "options": ["A. 友谊很重要", "B. 如何维系异地友谊",
                 "C. 视频通话的五个好处", "D. 友谊的历史起源"], "answer": "B",
     "explain": "高频词同时指向「友谊」与「距离／保持联系」，最完整的概括是异地友谊的维系。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "主旨大意题", "variant": "过宽过窄排除", "kind": "choice",
     "stem": "全文只谈异地友谊，某选项写成「友谊很重要」。该选项的问题是什么？",
     "options": ["A. 过宽", "B. 过窄", "C. 偏题", "D. 没有问题"], "answer": "A",
     "explain": "把只涉及一种情形的文章泛化成一个人人都知道的大道理，属于过宽。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "主旨大意题", "variant": "过宽过窄排除", "kind": "choice",
     "stem": "主旨题的四条选项里，合格的唯一标准是？",
     "options": ["A. 能覆盖全文的话题", "B. 用词与原文完全相同",
                 "C. 字数最长", "D. 字数最短"], "answer": "A",
     "explain": "过宽与过窄都不合格；能否覆盖全文是判定的唯一标准，与长短、用词无关。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},

    # ---------- 标题归纳题（变体：主题词加角度 / 过宽 / 过窄 / 警惕细节命名） ----------
    {"node": "标题归纳题", "variant": "主题词加角度", "kind": "choice",
     "stem": "标题归纳题可以看作哪一类题的最短版本？",
     "options": ["A. 主旨大意题", "B. 细节理解题", "C. 词句猜测题", "D. 观点态度题"], "answer": "A",
     "explain": "标题题与主旨题判定标准一致（都必须覆盖全文），只是形式更短。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "标题归纳题", "variant": "主题词加角度", "kind": "choice",
     "stem": "合格的标题通常由什么构成？",
     "options": ["A. 主题词加一个动作或角度", "B. 尽可能多的细节",
                 "C. 文中出现的全部专有名词", "D. 作者的姓名与身份"], "answer": "A",
     "explain": "主题词保证覆盖全文，动作或角度保证标题具体、不空泛。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "标题归纳题", "variant": "过宽", "kind": "choice",
     "stem": "把剑桥的一项实验结论概括成 Beauty Is Important 来当标题，问题在于？",
     "options": ["A. 过宽", "B. 过窄", "C. 偏题", "D. 太长"], "answer": "A",
     "explain": "把具体实验泛化成一句常识，读者看不出文章在讲什么，属于过宽。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "标题归纳题", "variant": "过宽", "kind": "choice",
     "stem": "合格的标题是否需要覆盖全文的每一个要点？",
     "options": ["A. 必须全部覆盖", "B. 不必逐点覆盖，但不能偏离全文话题",
                 "C. 完全不需要覆盖", "D. 只需覆盖第一段"], "answer": "B",
     "explain": "标题要短，不要求逐点写全；但话题范围必须与全文一致，否则就是过窄或偏题。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "标题归纳题", "variant": "过窄", "kind": "choice",
     "stem": "某文讲「纽约大规模植树，却因某些树种助推近地面臭氧」。把标题定为 How to Plant Trees in New York，问题在于？",
     "options": ["A. 过宽", "B. 过窄", "C. 偏题", "D. 太长"], "answer": "B",
     "explain": "只抓住了第一段的动作，丢掉了全文关于意外代价的转折，属于过窄。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "标题归纳题", "variant": "过窄", "kind": "choice",
     "stem": "下列哪一项最像合格的标题？",
     "options": ["A. 一个模糊的大道理", "B. 主题词与关键关系的组合",
                 "C. 文中某一句里的专有名词", "D. 一个与全文无关的问句"], "answer": "B",
     "explain": "主题词定话题、关键关系定角度，两者结合才能既覆盖全文又具体不空泛。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "标题归纳题", "variant": "警惕细节命名", "kind": "choice",
     "stem": "某选项用文中只出现过一次的专有名词来当标题，通常说明？",
     "options": ["A. 它是用来把你引偏的干扰项", "B. 它是正确答案",
                 "C. 说明该名词最重要", "D. 说明文章以该名词为主题"], "answer": "A",
     "explain": "标题要概括全文，用一个生僻细节点命名的选项往往只覆盖一句话。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "标题归纳题", "variant": "警惕细节命名", "kind": "choice",
     "stem": "标题题与主旨题的关系是？",
     "options": ["A. 判定标准一致，只是标题更短更抓人", "B. 两者完全无关",
                 "C. 标题只需好看，不必覆盖全文", "D. 标题必须包含全文所有要点"], "answer": "A",
     "explain": "两者都以「覆盖全文」为底线；差别只在形式——标题更短、更讲求抓人。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},

    # ---------- 观点态度与写作意图（变体：作者与引语 / 让步转折 / 客观态度 / 意图定档） ----------
    {"node": "观点态度与写作意图", "variant": "作者与引语", "kind": "choice",
     "stem": "带感情色彩的形容词出现在直接引语里，通常说明什么？",
     "options": ["A. 那是文中人物的态度", "B. 那一定就是作者的态度",
                 "C. 与态度题无关", "D. 那说明文章是应用文"], "answer": "A",
     "explain": "引语表达的是被引用者的态度；作者的态度要另找自己的评述句。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "观点态度与写作意图", "variant": "作者与引语", "kind": "choice",
     "stem": "作者在文中引用他人的评价，是否等于作者本人赞同该评价？",
     "options": ["A. 等于", "B. 不等于", "C. 视引用字数而定", "D. 视文章长度而定"], "answer": "B",
     "explain": "引用只是呈现他人观点；作者是否赞同，要看作者自己的措辞与落脚点。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "观点态度与写作意图", "variant": "让步转折", "kind": "choice",
     "stem": "Though the idea looks attractive, the evidence is far from convincing. 作者的态度是？",
     "options": ["A. 支持", "B. 怀疑", "C. 无所谓", "D. 兴奋"], "answer": "B",
     "explain": "让步在先、转折在后，far from convincing 说明作者对现有证据持怀疑态度。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "观点态度与写作意图", "variant": "让步转折", "kind": "choice",
     "stem": "文中出现让步从句时，作者真正的落脚点通常在？",
     "options": ["A. 让步从句里", "B. 主句里", "C. 上一句里", "D. 标题里"], "answer": "B",
     "explain": "让步从句只是先退一步，主句才承载作者的真实立场。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "观点态度与写作意图", "variant": "客观态度", "kind": "choice",
     "stem": "某文全篇解释现象、引用数据、不作评价。作者的态度应定为？",
     "options": ["A. positive", "B. negative", "C. objective", "D. angry"], "answer": "C",
     "explain": "只陈述事实与数据、不置评论，正是客观（objective）态度。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "观点态度与写作意图", "variant": "客观态度", "kind": "choice",
     "stem": "objective 这个态度标签的确切含义是？",
     "options": ["A. 没有态度", "B. 只陈述事实与数据、不作评价",
                 "C. 强烈支持", "D. 强烈反对"], "answer": "B",
     "explain": "objective 本身就是一种被明确考查的态度，不等于「没有态度」。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "观点态度与写作意图", "variant": "意图定档", "kind": "choice",
     "stem": "图书馆使用指南这类文本，作者的写作意图通常是？",
     "options": ["A. to inform", "B. to persuade", "C. to entertain", "D. to criticise"], "answer": "A",
     "explain": "说明性指南的目的是告知读者规则与流程，属 to inform。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
    {"node": "观点态度与写作意图", "variant": "意图定档", "kind": "choice",
     "stem": "倡议信与公益广告这类文本，写作意图通常是？",
     "options": ["A. to inform", "B. to persuade", "C. to entertain", "D. to explain"], "answer": "B",
     "explain": "倡议与广告的目标是说服读者采取行动，属 to persuade；先定文体即可定档。",
     "source": "自编练习（2026-09-22，未人工复核）", "verified": False},
]
